SIM   ?= icarus
WAVES ?= 1
TOPLEVEL_LANG ?= verilog

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

DUT      = rocev2_top
TOPLEVEL = $(DUT)_top
MODULE   = test_$(DUT)

VERILOG_SOURCES += ../verilog/rocev2_top_append_payload_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_Block_entry49_proc.v
# VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s_conn_table_remote_ip_address_V_RAM_AUTO_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s_conn_table_remote_ip_address_V_RAM_AUTO_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s_conn_table_remote_qpn_V_RAM_AUTO_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s_conn_table_remote_qpn_V_RAM_AUTO_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s_conn_table_remote_udp_port_V_RAM_AUTO_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s_conn_table_remote_udp_port_V_RAM_AUTO_1R1W.v
VERILOG_SOURCES += ../verilog/rocev2_top_conn_table_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_convert_axis_to_net_axis_512_1.v
VERILOG_SOURCES += ../verilog/rocev2_top_convert_axis_to_net_axis_512_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_convert_net_axis_to_axis_512_2.v
VERILOG_SOURCES += ../verilog/rocev2_top_convert_net_axis_to_axis_512_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_drop_ooo_ibh_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_entry_proc.v
VERILOG_SOURCES += ../verilog/rocev2_top_extract_icrc_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w1024_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w1024_d32_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w1024_d4_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w1024_d8_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w113_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w119_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w123_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w128_d16_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w128_d3_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w138_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w145_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w145_d8_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w150_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w150_d512_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w153_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w16_d2000_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w16_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w16_d4_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w178_d4_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w178_d512_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w192_d8_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w1_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w23_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w24_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w256_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w256_d32_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w256_d8_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w2_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w320_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w320_d8_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w32_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w384_d8_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w3_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w41_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w448_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w45_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w48_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w49_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w4_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w50_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w50_d32_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w56_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w64_d128_A.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w64_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w75_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w96_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_fifo_w97_d2_S.v
VERILOG_SOURCES += ../verilog/rocev2_top_freelist_handler_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_generate_exh_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_generate_ibh_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_generate_udp_512_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_handle_read_requests_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_hls_deadlock_detection_unit.v
# VERILOG_SOURCES += ../verilog/rocev2_top_hls_deadlock_detector.vh
VERILOG_SOURCES += ../verilog/rocev2_top_hls_deadlock_idx0_monitor.v
# VERILOG_SOURCES += ../verilog/rocev2_top_hls_deadlock_kernel_monitor_top.vh
# VERILOG_SOURCES += ../verilog/rocev2_top_hls_deadlock_report_unit.vh
VERILOG_SOURCES += ../verilog/rocev2_top_insert_icrc_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_ipUdpMetaHandler_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_ipv4_drop_optional_ip_header_512_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_ipv4_generate_ipv4_512_3.v
VERILOG_SOURCES += ../verilog/rocev2_top_ipv4_lshiftWordByOctet_512_2_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_local_req_handler_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_lshiftWordByOctet_512_11_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_lshiftWordByOctet_512_12_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_lshiftWordByOctet_512_13_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_mem_cmd_merger_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_merge_retrans_request.v
VERILOG_SOURCES += ../verilog/rocev2_top_merge_rx_meta.v
VERILOG_SOURCES += ../verilog/rocev2_top_merge_rx_pkgs_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_meta_merger_0_s.v
# VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s_msn_table_dma_length_V_RAM_2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s_msn_table_dma_length_V_RAM_2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s_msn_table_lst_V_RAM_2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s_msn_table_lst_V_RAM_2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s_msn_table_vaddr_V_RAM_2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s_msn_table_vaddr_V_RAM_2P_BRAM_1R1W.v
VERILOG_SOURCES += ../verilog/rocev2_top_msn_table_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_mux_50016_1_1_1.v
VERILOG_SOURCES += ../verilog/rocev2_top_prepend_ibh_header_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_process_ipv4_512_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_process_retransmissions_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_process_udp_512_4.v
VERILOG_SOURCES += ../verilog/rocev2_top_qp_interface_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_regslice_both.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_localAddr_V_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_localAddr_V_RAM_T2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_lst_V_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_lst_V_RAM_T2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_next_V_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_next_V_RAM_T2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_offs_V_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_offs_V_RAM_T2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_opCode_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_opCode_RAM_T2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_psn_V_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s_meta_table_psn_V_RAM_T2P_BRAM_1R1W.v
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_meta_table_0_s.v
# VERILOG_SOURCES += ../verilog/rocev2_top_retrans_pointer_table_0_s_ptr_table_head_V_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_pointer_table_0_s_ptr_table_head_V_RAM_T2P_BRAM_1R1W.v
VERILOG_SOURCES += ../verilog/rocev2_top_retrans_pointer_table_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rshiftWordByOctet_net_axis_512_512_11_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rshiftWordByOctet_net_axis_512_512_12_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rshiftWordByOctet_net_axis_512_512_13_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rx_exh_fsm_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rx_exh_payload_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rx_ibh_fsm_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rx_process_exh_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_rx_process_ibh_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_split_tx_meta.v
# VERILOG_SOURCES += ../verilog/rocev2_top_state_table_0_s_state_table_req_old_unack_V_RAM_2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_state_table_0_s_state_table_req_old_unack_V_RAM_2P_BRAM_1R1W.v
# VERILOG_SOURCES += ../verilog/rocev2_top_state_table_0_s_state_table_retryCounter_V_RAM_2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_state_table_0_s_state_table_retryCounter_V_RAM_2P_BRAM_1R1W.v
VERILOG_SOURCES += ../verilog/rocev2_top_state_table_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_stream_merger_ackEvent_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_top.v
# VERILOG_SOURCES += ../verilog/rocev2_top_transport_timer_0_s_transportTimerTable_RAM_T2P_BRAM_1R1W.dat
VERILOG_SOURCES += ../verilog/rocev2_top_transport_timer_0_s_transportTimerTable_RAM_T2P_BRAM_1R1W.v
VERILOG_SOURCES += ../verilog/rocev2_top_transport_timer_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_tx_ipUdpMetaMerger_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_tx_pkg_arbiter_512_0_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_udp_lshiftWordByOctet_512_1_s.v
VERILOG_SOURCES += ../verilog/rocev2_top_udp_rshiftWordByOctet_net_axis_512_512_2_s.v
VERILOG_SOURCES += ../verilog/rocev2_top.v

ifeq ($(SIM), icarus)
	PLUSARGS += -fst

	COMPILE_ARGS += $(foreach v,$(filter PARAM_%,$(.VARIABLES)),-P $(TOPLEVEL).$(subst PARAM_,,$(v))=$($(v)))

	ifeq ($(WAVES), 1)
		VERILOG_SOURCES += iverilog_dump.v
		COMPILE_ARGS += -s iverilog_dump
	endif
else ifeq ($(SIM), verilator)
	COMPILE_ARGS += -Wno-SELRANGE -Wno-WIDTH

	COMPILE_ARGS += $(foreach v,$(filter PARAM_%,$(.VARIABLES)),-G$(subst PARAM_,,$(v))=$($(v)))

	ifeq ($(WAVES), 1)
		COMPILE_ARGS += --trace-fst
	endif
endif

include $(shell cocotb-config --makefiles)/Makefile.sim

iverilog_dump.v:
	echo 'module iverilog_dump();' > $@
	echo 'initial begin' >> $@
	echo '    $$dumpfile("$(TOPLEVEL).fst");' >> $@
	echo '    $$dumpvars(0, $(TOPLEVEL));' >> $@
	echo 'end' >> $@
	echo 'endmodule' >> $@

clean::
	@rm -rf iverilog_dump.v
	@rm -rf dump.fst $(TOPLEVEL).fst
