-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_retrans_meta_table_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rt_metaReqFifo_dout : IN STD_LOGIC_VECTOR (383 downto 0);
    rt_metaReqFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rt_metaReqFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rt_metaReqFifo_empty_n : IN STD_LOGIC;
    rt_metaReqFifo_read : OUT STD_LOGIC;
    rt_metaRspFifo_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    rt_metaRspFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rt_metaRspFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rt_metaRspFifo_full_n : IN STD_LOGIC;
    rt_metaRspFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_retrans_meta_table_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv384_lc_29 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100100000";
    constant ap_const_lv32_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101000";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv384_lc_30 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100110000";
    constant ap_const_lv384_lc_31 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100111000";
    constant ap_const_lv384_lc_32 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101000000";
    constant ap_const_lv384_lc_33 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_118_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_i_reg_519 : STD_LOGIC_VECTOR (0 downto 0);
    signal req_write_reg_523 : STD_LOGIC_VECTOR (0 downto 0);
    signal req_append_reg_527 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op97_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal meta_table_psn_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_psn_V_ce0 : STD_LOGIC;
    signal meta_table_psn_V_we0 : STD_LOGIC;
    signal meta_table_psn_V_d0 : STD_LOGIC_VECTOR (23 downto 0);
    signal meta_table_psn_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal meta_table_next_V_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_next_V_1_ce0 : STD_LOGIC;
    signal meta_table_next_V_1_we0 : STD_LOGIC;
    signal meta_table_next_V_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal meta_table_next_V_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal meta_table_opCode_V_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_opCode_V_1_ce0 : STD_LOGIC;
    signal meta_table_opCode_V_1_we0 : STD_LOGIC;
    signal meta_table_opCode_V_1_d0 : STD_LOGIC_VECTOR (4 downto 0);
    signal meta_table_opCode_V_1_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal meta_table_localAddr_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_localAddr_V_ce0 : STD_LOGIC;
    signal meta_table_localAddr_V_we0 : STD_LOGIC;
    signal meta_table_localAddr_V_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal meta_table_localAddr_V_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal meta_table_remoteAddr_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_remoteAddr_V_ce0 : STD_LOGIC;
    signal meta_table_remoteAddr_V_we0 : STD_LOGIC;
    signal meta_table_remoteAddr_V_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal meta_table_remoteAddr_V_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal meta_table_length_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_length_V_ce0 : STD_LOGIC;
    signal meta_table_length_V_we0 : STD_LOGIC;
    signal meta_table_length_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal meta_table_length_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal meta_table_lst_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_lst_V_ce0 : STD_LOGIC;
    signal meta_table_lst_V_we0 : STD_LOGIC;
    signal meta_table_lst_V_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal meta_table_lst_V_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal meta_table_offs_V_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_offs_V_ce0 : STD_LOGIC;
    signal meta_table_offs_V_we0 : STD_LOGIC;
    signal meta_table_offs_V_d0 : STD_LOGIC_VECTOR (3 downto 0);
    signal meta_table_offs_V_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal meta_table_valid_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_valid_1_ce0 : STD_LOGIC;
    signal meta_table_valid_1_we0 : STD_LOGIC;
    signal meta_table_valid_1_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal meta_table_valid_1_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal meta_table_isTail_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_isTail_1_ce0 : STD_LOGIC;
    signal meta_table_isTail_1_we0 : STD_LOGIC;
    signal meta_table_isTail_1_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal meta_table_isTail_1_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal rt_metaReqFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rt_metaRspFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal req_write_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal req_append_fu_450_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln541_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal meta_table_psn_V_addr_gep_fu_270_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_opCode_V_1_addr_gep_fu_277_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_localAddr_V_addr_gep_fu_284_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_remoteAddr_V_addr_gep_fu_291_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_length_V_addr_gep_fu_298_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_lst_V_addr_gep_fu_305_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_offs_V_addr_gep_fu_312_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal meta_table_valid_1_addr_gep_fu_319_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal req_idx_V_fu_334_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_247_i_fu_480_p16 : STD_LOGIC_VECTOR (248 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op61_store_state1 : BOOLEAN;
    signal ap_enable_operation_61 : BOOLEAN;
    signal ap_enable_state1_pp0_iter0_stage0 : BOOLEAN;
    signal ap_predicate_op52_load_state1 : BOOLEAN;
    signal ap_enable_operation_52 : BOOLEAN;
    signal ap_predicate_op86_load_state2 : BOOLEAN;
    signal ap_enable_operation_86 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op74_store_state1 : BOOLEAN;
    signal ap_enable_operation_74 : BOOLEAN;
    signal ap_predicate_op62_store_state1 : BOOLEAN;
    signal ap_enable_operation_62 : BOOLEAN;
    signal ap_predicate_op60_load_state1 : BOOLEAN;
    signal ap_enable_operation_60 : BOOLEAN;
    signal ap_predicate_op94_load_state2 : BOOLEAN;
    signal ap_enable_operation_94 : BOOLEAN;
    signal ap_predicate_op82_store_state1 : BOOLEAN;
    signal ap_enable_operation_82 : BOOLEAN;
    signal ap_predicate_op73_store_state1 : BOOLEAN;
    signal ap_enable_operation_73 : BOOLEAN;
    signal ap_predicate_op51_load_state1 : BOOLEAN;
    signal ap_enable_operation_51 : BOOLEAN;
    signal ap_predicate_op85_load_state2 : BOOLEAN;
    signal ap_enable_operation_85 : BOOLEAN;
    signal ap_predicate_op75_store_state1 : BOOLEAN;
    signal ap_enable_operation_75 : BOOLEAN;
    signal ap_predicate_op53_load_state1 : BOOLEAN;
    signal ap_enable_operation_53 : BOOLEAN;
    signal ap_predicate_op87_load_state2 : BOOLEAN;
    signal ap_enable_operation_87 : BOOLEAN;
    signal ap_predicate_op76_store_state1 : BOOLEAN;
    signal ap_enable_operation_76 : BOOLEAN;
    signal ap_predicate_op54_load_state1 : BOOLEAN;
    signal ap_enable_operation_54 : BOOLEAN;
    signal ap_predicate_op88_load_state2 : BOOLEAN;
    signal ap_enable_operation_88 : BOOLEAN;
    signal ap_predicate_op77_store_state1 : BOOLEAN;
    signal ap_enable_operation_77 : BOOLEAN;
    signal ap_predicate_op55_load_state1 : BOOLEAN;
    signal ap_enable_operation_55 : BOOLEAN;
    signal ap_predicate_op89_load_state2 : BOOLEAN;
    signal ap_enable_operation_89 : BOOLEAN;
    signal ap_predicate_op78_store_state1 : BOOLEAN;
    signal ap_enable_operation_78 : BOOLEAN;
    signal ap_predicate_op56_load_state1 : BOOLEAN;
    signal ap_enable_operation_56 : BOOLEAN;
    signal ap_predicate_op90_load_state2 : BOOLEAN;
    signal ap_enable_operation_90 : BOOLEAN;
    signal ap_predicate_op79_store_state1 : BOOLEAN;
    signal ap_enable_operation_79 : BOOLEAN;
    signal ap_predicate_op57_load_state1 : BOOLEAN;
    signal ap_enable_operation_57 : BOOLEAN;
    signal ap_predicate_op91_load_state2 : BOOLEAN;
    signal ap_enable_operation_91 : BOOLEAN;
    signal ap_predicate_op80_store_state1 : BOOLEAN;
    signal ap_enable_operation_80 : BOOLEAN;
    signal ap_predicate_op58_load_state1 : BOOLEAN;
    signal ap_enable_operation_58 : BOOLEAN;
    signal ap_predicate_op92_load_state2 : BOOLEAN;
    signal ap_enable_operation_92 : BOOLEAN;
    signal ap_predicate_op81_store_state1 : BOOLEAN;
    signal ap_enable_operation_81 : BOOLEAN;
    signal ap_predicate_op59_load_state1 : BOOLEAN;
    signal ap_enable_operation_59 : BOOLEAN;
    signal ap_predicate_op93_load_state2 : BOOLEAN;
    signal ap_enable_operation_93 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_181 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rocev2_top_retrans_meta_table_0_s_meta_table_psn_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component rocev2_top_retrans_meta_table_0_s_meta_table_next_V_1_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component rocev2_top_retrans_meta_table_0_s_meta_table_opCode_V_1_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (4 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component rocev2_top_retrans_meta_table_0_s_meta_table_localAddr_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component rocev2_top_retrans_meta_table_0_s_meta_table_length_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rocev2_top_retrans_meta_table_0_s_meta_table_lst_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component rocev2_top_retrans_meta_table_0_s_meta_table_offs_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (3 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    meta_table_psn_V_U : component rocev2_top_retrans_meta_table_0_s_meta_table_psn_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_psn_V_address0,
        ce0 => meta_table_psn_V_ce0,
        we0 => meta_table_psn_V_we0,
        d0 => meta_table_psn_V_d0,
        q0 => meta_table_psn_V_q0);

    meta_table_next_V_1_U : component rocev2_top_retrans_meta_table_0_s_meta_table_next_V_1_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_next_V_1_address0,
        ce0 => meta_table_next_V_1_ce0,
        we0 => meta_table_next_V_1_we0,
        d0 => meta_table_next_V_1_d0,
        q0 => meta_table_next_V_1_q0);

    meta_table_opCode_V_1_U : component rocev2_top_retrans_meta_table_0_s_meta_table_opCode_V_1_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 5,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_opCode_V_1_address0,
        ce0 => meta_table_opCode_V_1_ce0,
        we0 => meta_table_opCode_V_1_we0,
        d0 => meta_table_opCode_V_1_d0,
        q0 => meta_table_opCode_V_1_q0);

    meta_table_localAddr_V_U : component rocev2_top_retrans_meta_table_0_s_meta_table_localAddr_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_localAddr_V_address0,
        ce0 => meta_table_localAddr_V_ce0,
        we0 => meta_table_localAddr_V_we0,
        d0 => meta_table_localAddr_V_d0,
        q0 => meta_table_localAddr_V_q0);

    meta_table_remoteAddr_V_U : component rocev2_top_retrans_meta_table_0_s_meta_table_localAddr_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_remoteAddr_V_address0,
        ce0 => meta_table_remoteAddr_V_ce0,
        we0 => meta_table_remoteAddr_V_we0,
        d0 => meta_table_remoteAddr_V_d0,
        q0 => meta_table_remoteAddr_V_q0);

    meta_table_length_V_U : component rocev2_top_retrans_meta_table_0_s_meta_table_length_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_length_V_address0,
        ce0 => meta_table_length_V_ce0,
        we0 => meta_table_length_V_we0,
        d0 => meta_table_length_V_d0,
        q0 => meta_table_length_V_q0);

    meta_table_lst_V_U : component rocev2_top_retrans_meta_table_0_s_meta_table_lst_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_lst_V_address0,
        ce0 => meta_table_lst_V_ce0,
        we0 => meta_table_lst_V_we0,
        d0 => meta_table_lst_V_d0,
        q0 => meta_table_lst_V_q0);

    meta_table_offs_V_U : component rocev2_top_retrans_meta_table_0_s_meta_table_offs_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 4,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_offs_V_address0,
        ce0 => meta_table_offs_V_ce0,
        we0 => meta_table_offs_V_we0,
        d0 => meta_table_offs_V_d0,
        q0 => meta_table_offs_V_q0);

    meta_table_valid_1_U : component rocev2_top_retrans_meta_table_0_s_meta_table_lst_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_valid_1_address0,
        ce0 => meta_table_valid_1_ce0,
        we0 => meta_table_valid_1_we0,
        d0 => meta_table_valid_1_d0,
        q0 => meta_table_valid_1_q0);

    meta_table_isTail_1_U : component rocev2_top_retrans_meta_table_0_s_meta_table_lst_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 2000,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => meta_table_isTail_1_address0,
        ce0 => meta_table_isTail_1_ce0,
        we0 => meta_table_isTail_1_we0,
        d0 => meta_table_isTail_1_d0,
        q0 => meta_table_isTail_1_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                req_append_reg_527 <= rt_metaReqFifo_dout(328 downto 328);
                req_write_reg_523 <= rt_metaReqFifo_dout(320 downto 320);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_i_reg_519 <= tmp_i_nbreadreq_fu_118_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rt_metaReqFifo_empty_n, tmp_i_nbreadreq_fu_118_p3, ap_done_reg, rt_metaRspFifo_full_n, ap_predicate_op97_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op97_write_state2 = ap_const_boolean_1) and (rt_metaRspFifo_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (rt_metaReqFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rt_metaReqFifo_empty_n, tmp_i_nbreadreq_fu_118_p3, ap_done_reg, rt_metaRspFifo_full_n, ap_predicate_op97_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op97_write_state2 = ap_const_boolean_1) and (rt_metaRspFifo_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (rt_metaReqFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rt_metaReqFifo_empty_n, tmp_i_nbreadreq_fu_118_p3, ap_done_reg, rt_metaRspFifo_full_n, ap_predicate_op97_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op97_write_state2 = ap_const_boolean_1) and (rt_metaRspFifo_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (rt_metaReqFifo_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rt_metaReqFifo_empty_n, tmp_i_nbreadreq_fu_118_p3, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (rt_metaReqFifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rt_metaRspFifo_full_n, ap_predicate_op97_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op97_write_state2 = ap_const_boolean_1) and (rt_metaRspFifo_full_n = ap_const_logic_0));
    end process;


    ap_condition_181_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0)
    begin
                ap_condition_181 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_51_assign_proc : process(ap_predicate_op51_load_state1)
    begin
                ap_enable_operation_51 <= (ap_predicate_op51_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_52_assign_proc : process(ap_predicate_op52_load_state1)
    begin
                ap_enable_operation_52 <= (ap_predicate_op52_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_53_assign_proc : process(ap_predicate_op53_load_state1)
    begin
                ap_enable_operation_53 <= (ap_predicate_op53_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_54_assign_proc : process(ap_predicate_op54_load_state1)
    begin
                ap_enable_operation_54 <= (ap_predicate_op54_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_55_assign_proc : process(ap_predicate_op55_load_state1)
    begin
                ap_enable_operation_55 <= (ap_predicate_op55_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_56_assign_proc : process(ap_predicate_op56_load_state1)
    begin
                ap_enable_operation_56 <= (ap_predicate_op56_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_57_assign_proc : process(ap_predicate_op57_load_state1)
    begin
                ap_enable_operation_57 <= (ap_predicate_op57_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_58_assign_proc : process(ap_predicate_op58_load_state1)
    begin
                ap_enable_operation_58 <= (ap_predicate_op58_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_59_assign_proc : process(ap_predicate_op59_load_state1)
    begin
                ap_enable_operation_59 <= (ap_predicate_op59_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_60_assign_proc : process(ap_predicate_op60_load_state1)
    begin
                ap_enable_operation_60 <= (ap_predicate_op60_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_61_assign_proc : process(ap_predicate_op61_store_state1)
    begin
                ap_enable_operation_61 <= (ap_predicate_op61_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_62_assign_proc : process(ap_predicate_op62_store_state1)
    begin
                ap_enable_operation_62 <= (ap_predicate_op62_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_73_assign_proc : process(ap_predicate_op73_store_state1)
    begin
                ap_enable_operation_73 <= (ap_predicate_op73_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_74_assign_proc : process(ap_predicate_op74_store_state1)
    begin
                ap_enable_operation_74 <= (ap_predicate_op74_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_75_assign_proc : process(ap_predicate_op75_store_state1)
    begin
                ap_enable_operation_75 <= (ap_predicate_op75_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_76_assign_proc : process(ap_predicate_op76_store_state1)
    begin
                ap_enable_operation_76 <= (ap_predicate_op76_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_77_assign_proc : process(ap_predicate_op77_store_state1)
    begin
                ap_enable_operation_77 <= (ap_predicate_op77_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_78_assign_proc : process(ap_predicate_op78_store_state1)
    begin
                ap_enable_operation_78 <= (ap_predicate_op78_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_79_assign_proc : process(ap_predicate_op79_store_state1)
    begin
                ap_enable_operation_79 <= (ap_predicate_op79_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_80_assign_proc : process(ap_predicate_op80_store_state1)
    begin
                ap_enable_operation_80 <= (ap_predicate_op80_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_81_assign_proc : process(ap_predicate_op81_store_state1)
    begin
                ap_enable_operation_81 <= (ap_predicate_op81_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_82_assign_proc : process(ap_predicate_op82_store_state1)
    begin
                ap_enable_operation_82 <= (ap_predicate_op82_store_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_85_assign_proc : process(ap_predicate_op85_load_state2)
    begin
                ap_enable_operation_85 <= (ap_predicate_op85_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_86_assign_proc : process(ap_predicate_op86_load_state2)
    begin
                ap_enable_operation_86 <= (ap_predicate_op86_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_87_assign_proc : process(ap_predicate_op87_load_state2)
    begin
                ap_enable_operation_87 <= (ap_predicate_op87_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_88_assign_proc : process(ap_predicate_op88_load_state2)
    begin
                ap_enable_operation_88 <= (ap_predicate_op88_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_89_assign_proc : process(ap_predicate_op89_load_state2)
    begin
                ap_enable_operation_89 <= (ap_predicate_op89_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_90_assign_proc : process(ap_predicate_op90_load_state2)
    begin
                ap_enable_operation_90 <= (ap_predicate_op90_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_91_assign_proc : process(ap_predicate_op91_load_state2)
    begin
                ap_enable_operation_91 <= (ap_predicate_op91_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_92_assign_proc : process(ap_predicate_op92_load_state2)
    begin
                ap_enable_operation_92 <= (ap_predicate_op92_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_93_assign_proc : process(ap_predicate_op93_load_state2)
    begin
                ap_enable_operation_93 <= (ap_predicate_op93_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_94_assign_proc : process(ap_predicate_op94_load_state2)
    begin
                ap_enable_operation_94 <= (ap_predicate_op94_load_state2 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_enable_state1_pp0_iter0_stage0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0)
    begin
                ap_enable_state1_pp0_iter0_stage0 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op51_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op51_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op52_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op52_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op53_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op53_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op54_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op54_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op55_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op55_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op56_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op56_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op57_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op57_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op58_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op58_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op59_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op59_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op60_load_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op60_load_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op61_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op61_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op62_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
                ap_predicate_op62_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op73_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op73_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op74_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op74_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op75_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op75_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op76_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op76_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op77_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op77_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op78_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op78_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op79_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op79_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op80_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op80_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op81_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op81_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op82_store_state1_assign_proc : process(tmp_i_nbreadreq_fu_118_p3, req_write_fu_442_p3)
    begin
                ap_predicate_op82_store_state1 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op85_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op85_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op86_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op86_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op87_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op87_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op88_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op88_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op89_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op89_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op90_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op90_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op91_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op91_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op92_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op92_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op93_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op93_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op94_load_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op94_load_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_predicate_op97_write_state2_assign_proc : process(tmp_i_reg_519, req_write_reg_523, req_append_reg_527)
    begin
                ap_predicate_op97_write_state2 <= ((req_append_reg_527 = ap_const_lv1_0) and (req_write_reg_523 = ap_const_lv1_0) and (tmp_i_reg_519 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_isTail_1_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_isTail_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_isTail_1_ce0 <= ap_const_logic_1;
        else 
            meta_table_isTail_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    meta_table_isTail_1_d0_assign_proc : process(rt_metaReqFifo_dout, req_write_fu_442_p3, req_append_fu_450_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_isTail_1_d0 <= rt_metaReqFifo_dout(312 downto 312);
            elsif (((req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_isTail_1_d0 <= ap_const_lv1_0;
            else 
                meta_table_isTail_1_d0 <= "X";
            end if;
        else 
            meta_table_isTail_1_d0 <= "X";
        end if; 
    end process;


    meta_table_isTail_1_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)))) then 
            meta_table_isTail_1_we0 <= ap_const_logic_1;
        else 
            meta_table_isTail_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_length_V_addr_gep_fu_298_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_length_V_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_length_V_addr_gep_fu_298_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_length_V_address0 <= meta_table_length_V_addr_gep_fu_298_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_length_V_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_length_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_length_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_length_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_length_V_ce0 <= ap_const_logic_1;
        else 
            meta_table_length_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_length_V_d0 <= rt_metaReqFifo_dout(287 downto 256);

    meta_table_length_V_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_length_V_we0 <= ap_const_logic_1;
        else 
            meta_table_length_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_localAddr_V_addr_gep_fu_284_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_localAddr_V_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_localAddr_V_addr_gep_fu_284_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_localAddr_V_address0 <= meta_table_localAddr_V_addr_gep_fu_284_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_localAddr_V_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_localAddr_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_localAddr_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_localAddr_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_localAddr_V_ce0 <= ap_const_logic_1;
        else 
            meta_table_localAddr_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_localAddr_V_d0 <= rt_metaReqFifo_dout(191 downto 128);

    meta_table_localAddr_V_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_localAddr_V_we0 <= ap_const_logic_1;
        else 
            meta_table_localAddr_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_lst_V_addr_gep_fu_305_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_lst_V_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_lst_V_addr_gep_fu_305_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_lst_V_address0 <= meta_table_lst_V_addr_gep_fu_305_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_lst_V_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_lst_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_lst_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_lst_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_lst_V_ce0 <= ap_const_logic_1;
        else 
            meta_table_lst_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_lst_V_d0 <= rt_metaReqFifo_dout(288 downto 288);

    meta_table_lst_V_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_lst_V_we0 <= ap_const_logic_1;
        else 
            meta_table_lst_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_next_V_1_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_next_V_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_next_V_1_ce0 <= ap_const_logic_1;
        else 
            meta_table_next_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_next_V_1_d0 <= rt_metaReqFifo_dout(111 downto 96);

    meta_table_next_V_1_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_1) and (req_write_fu_442_p3 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)))) then 
            meta_table_next_V_1_we0 <= ap_const_logic_1;
        else 
            meta_table_next_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_offs_V_addr_gep_fu_312_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_offs_V_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_offs_V_addr_gep_fu_312_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_offs_V_address0 <= meta_table_offs_V_addr_gep_fu_312_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_offs_V_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_offs_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_offs_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_offs_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_offs_V_ce0 <= ap_const_logic_1;
        else 
            meta_table_offs_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_offs_V_d0 <= rt_metaReqFifo_dout(299 downto 296);

    meta_table_offs_V_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_offs_V_we0 <= ap_const_logic_1;
        else 
            meta_table_offs_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_opCode_V_1_addr_gep_fu_277_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_opCode_V_1_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_opCode_V_1_addr_gep_fu_277_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_opCode_V_1_address0 <= meta_table_opCode_V_1_addr_gep_fu_277_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_opCode_V_1_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_opCode_V_1_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_opCode_V_1_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_opCode_V_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_opCode_V_1_ce0 <= ap_const_logic_1;
        else 
            meta_table_opCode_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_opCode_V_1_d0 <= rt_metaReqFifo_dout(116 downto 112);

    meta_table_opCode_V_1_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_opCode_V_1_we0 <= ap_const_logic_1;
        else 
            meta_table_opCode_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_psn_V_addr_gep_fu_270_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_psn_V_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_psn_V_addr_gep_fu_270_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_psn_V_address0 <= meta_table_psn_V_addr_gep_fu_270_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_psn_V_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_psn_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_psn_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_psn_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_psn_V_ce0 <= ap_const_logic_1;
        else 
            meta_table_psn_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_psn_V_d0 <= rt_metaReqFifo_dout(87 downto 64);

    meta_table_psn_V_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_psn_V_we0 <= ap_const_logic_1;
        else 
            meta_table_psn_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_remoteAddr_V_addr_gep_fu_291_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_remoteAddr_V_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_remoteAddr_V_addr_gep_fu_291_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_remoteAddr_V_address0 <= meta_table_remoteAddr_V_addr_gep_fu_291_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_remoteAddr_V_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_remoteAddr_V_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_remoteAddr_V_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_remoteAddr_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_remoteAddr_V_ce0 <= ap_const_logic_1;
        else 
            meta_table_remoteAddr_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_remoteAddr_V_d0 <= rt_metaReqFifo_dout(255 downto 192);

    meta_table_remoteAddr_V_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_remoteAddr_V_we0 <= ap_const_logic_1;
        else 
            meta_table_remoteAddr_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_valid_1_addr_gep_fu_319_p3 <= zext_ln541_fu_458_p1(11 - 1 downto 0);

    meta_table_valid_1_address0_assign_proc : process(req_write_fu_442_p3, req_append_fu_450_p3, zext_ln541_fu_458_p1, meta_table_valid_1_addr_gep_fu_319_p3, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((req_write_fu_442_p3 = ap_const_lv1_1)) then 
                meta_table_valid_1_address0 <= meta_table_valid_1_addr_gep_fu_319_p3;
            elsif (((req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0))) then 
                meta_table_valid_1_address0 <= zext_ln541_fu_458_p1(11 - 1 downto 0);
            else 
                meta_table_valid_1_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            meta_table_valid_1_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    meta_table_valid_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3, req_append_fu_450_p3)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_append_fu_450_p3 = ap_const_lv1_0) and (req_write_fu_442_p3 = ap_const_lv1_0)))) then 
            meta_table_valid_1_ce0 <= ap_const_logic_1;
        else 
            meta_table_valid_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    meta_table_valid_1_d0 <= rt_metaReqFifo_dout(304 downto 304);

    meta_table_valid_1_we0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001, req_write_fu_442_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (req_write_fu_442_p3 = ap_const_lv1_1))) then 
            meta_table_valid_1_we0 <= ap_const_logic_1;
        else 
            meta_table_valid_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    req_append_fu_450_p3 <= rt_metaReqFifo_dout(328 downto 328);
    req_idx_V_fu_334_p1 <= rt_metaReqFifo_dout(11 - 1 downto 0);
    req_write_fu_442_p3 <= rt_metaReqFifo_dout(320 downto 320);

    rt_metaReqFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rt_metaReqFifo_empty_n, tmp_i_nbreadreq_fu_118_p3, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rt_metaReqFifo_blk_n <= rt_metaReqFifo_empty_n;
        else 
            rt_metaReqFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rt_metaReqFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_118_p3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rt_metaReqFifo_read <= ap_const_logic_1;
        else 
            rt_metaReqFifo_read <= ap_const_logic_0;
        end if; 
    end process;


    rt_metaRspFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rt_metaRspFifo_full_n, ap_predicate_op97_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op97_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rt_metaRspFifo_blk_n <= rt_metaRspFifo_full_n;
        else 
            rt_metaRspFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rt_metaRspFifo_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_247_i_fu_480_p16),256));

    rt_metaRspFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op97_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op97_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rt_metaRspFifo_write <= ap_const_logic_1;
        else 
            rt_metaRspFifo_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_247_i_fu_480_p16 <= ((((((((((((((meta_table_isTail_1_q0 & ap_const_lv7_0) & meta_table_valid_1_q0) & ap_const_lv4_0) & meta_table_offs_V_q0) & ap_const_lv7_0) & meta_table_lst_V_q0) & meta_table_length_V_q0) & meta_table_remoteAddr_V_q0) & meta_table_localAddr_V_q0) & ap_const_lv11_0) & meta_table_opCode_V_1_q0) & meta_table_next_V_1_q0) & ap_const_lv8_0) & meta_table_psn_V_q0);
    tmp_i_nbreadreq_fu_118_p3 <= (0=>(rt_metaReqFifo_empty_n), others=>'-');
    zext_ln541_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(req_idx_V_fu_334_p1),64));
end behav;
