-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_QPContext_table_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_qp_conn_interface_TVALID : IN STD_LOGIC;
    qpif2QPC_upd_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    qpif2QPC_upd_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2QPC_upd_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2QPC_upd_empty_n : IN STD_LOGIC;
    qpif2QPC_upd_read : OUT STD_LOGIC;
    tx_ibhconnTable_req_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    tx_ibhconnTable_req_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_ibhconnTable_req_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    tx_ibhconnTable_req_empty_n : IN STD_LOGIC;
    tx_ibhconnTable_req_read : OUT STD_LOGIC;
    wqecqe2connTable_req_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    wqecqe2connTable_req_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    wqecqe2connTable_req_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    wqecqe2connTable_req_empty_n : IN STD_LOGIC;
    wqecqe2connTable_req_read : OUT STD_LOGIC;
    connTable2wqecqe_rsp_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    connTable2wqecqe_rsp_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    connTable2wqecqe_rsp_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    connTable2wqecqe_rsp_full_n : IN STD_LOGIC;
    connTable2wqecqe_rsp_write : OUT STD_LOGIC;
    tx_connTable2ibh_rsp_din : OUT STD_LOGIC_VECTOR (383 downto 0);
    tx_connTable2ibh_rsp_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    tx_connTable2ibh_rsp_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    tx_connTable2ibh_rsp_full_n : IN STD_LOGIC;
    tx_connTable2ibh_rsp_write : OUT STD_LOGIC;
    s_axis_qp_conn_interface_TDATA : IN STD_LOGIC_VECTOR (183 downto 0);
    s_axis_qp_conn_interface_TREADY : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_QPContext_table_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_B7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv104_0 : STD_LOGIC_VECTOR (103 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_96_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_i_reg_373 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_2644_nbreadreq_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op43_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal tmp_i_reg_373_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_2644_reg_397 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_386_i_nbreadreq_fu_124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op54_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal tmp_i_reg_373_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_2644_reg_397_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_386_i_reg_416 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_387_i_nbreadreq_fu_138_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op69_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal tmp_i_reg_373_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_2644_reg_397_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_386_i_reg_416_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_387_i_reg_435 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op83_write_state5 : BOOLEAN;
    signal ap_predicate_op88_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal conn_table_remote_qpn_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal conn_table_remote_qpn_V_ce0 : STD_LOGIC;
    signal conn_table_remote_qpn_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal conn_table_remote_qpn_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal conn_table_remote_qpn_V_ce1 : STD_LOGIC;
    signal conn_table_remote_qpn_V_we1 : STD_LOGIC;
    signal conn_table_remote_ip_address_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal conn_table_remote_ip_address_V_ce0 : STD_LOGIC;
    signal conn_table_remote_ip_address_V_q0 : STD_LOGIC_VECTOR (127 downto 0);
    signal conn_table_remote_ip_address_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal conn_table_remote_ip_address_V_ce1 : STD_LOGIC;
    signal conn_table_remote_ip_address_V_we1 : STD_LOGIC;
    signal conn_table_remote_udp_port_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal conn_table_remote_udp_port_V_ce0 : STD_LOGIC;
    signal conn_table_remote_udp_port_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal conn_table_remote_udp_port_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal conn_table_remote_udp_port_V_ce1 : STD_LOGIC;
    signal conn_table_remote_udp_port_V_we1 : STD_LOGIC;
    signal QPC_table_cq_id_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal QPC_table_cq_id_V_ce0 : STD_LOGIC;
    signal QPC_table_cq_id_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal QPC_table_cq_id_V_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal QPC_table_cq_id_V_ce1 : STD_LOGIC;
    signal QPC_table_cq_id_V_we1 : STD_LOGIC;
    signal s_axis_qp_conn_interface_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal qpif2QPC_upd_blk_n : STD_LOGIC;
    signal tx_ibhconnTable_req_blk_n : STD_LOGIC;
    signal tx_connTable2ibh_rsp_blk_n : STD_LOGIC;
    signal wqecqe2connTable_req_blk_n : STD_LOGIC;
    signal connTable2wqecqe_rsp_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ifRequest_qpn_V_fu_274_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ifRequest_qpn_V_reg_377 : STD_LOGIC_VECTOR (15 downto 0);
    signal ifRequest_remote_ip_address_V_reg_382 : STD_LOGIC_VECTOR (127 downto 0);
    signal ifRequest_remote_udp_port_V_reg_387 : STD_LOGIC_VECTOR (15 downto 0);
    signal ifRequest_remote_qpn_V_reg_392 : STD_LOGIC_VECTOR (23 downto 0);
    signal ifRequest_remote_qpn_V_reg_392_pp0_iter1_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal cqidUpd_local_qpn_V_fu_308_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal cqidUpd_local_qpn_V_reg_401 : STD_LOGIC_VECTOR (8 downto 0);
    signal cqidUpd_cq_id_V_reg_406 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln541_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_reg_411 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_14_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_14_reg_420 : STD_LOGIC_VECTOR (63 downto 0);
    signal conn_table_remote_ip_address_V_load_reg_454 : STD_LOGIC_VECTOR (127 downto 0);
    signal conn_table_remote_udp_port_V_load_reg_459 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln541_13_fu_333_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln541_15_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_500_i_fu_343_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_499_i_fu_358_p5 : STD_LOGIC_VECTOR (271 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_s_axis_qp_conn_interface_U_apdone_blk : STD_LOGIC;
    signal s_axis_qp_conn_interface_TDATA_int_regslice : STD_LOGIC_VECTOR (183 downto 0);
    signal s_axis_qp_conn_interface_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_qp_conn_interface_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_qp_conn_interface_U_ack_in : STD_LOGIC;
    signal ap_condition_430 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rocev2_top_QPContext_table_0_s_conn_table_remote_qpn_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component rocev2_top_QPContext_table_0_s_conn_table_remote_ip_address_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component rocev2_top_QPContext_table_0_s_conn_table_remote_udp_port_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component rocev2_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    conn_table_remote_qpn_V_U : component rocev2_top_QPContext_table_0_s_conn_table_remote_qpn_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conn_table_remote_qpn_V_address0,
        ce0 => conn_table_remote_qpn_V_ce0,
        q0 => conn_table_remote_qpn_V_q0,
        address1 => conn_table_remote_qpn_V_address1,
        ce1 => conn_table_remote_qpn_V_ce1,
        we1 => conn_table_remote_qpn_V_we1,
        d1 => ifRequest_remote_qpn_V_reg_392_pp0_iter1_reg);

    conn_table_remote_ip_address_V_U : component rocev2_top_QPContext_table_0_s_conn_table_remote_ip_address_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 128,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conn_table_remote_ip_address_V_address0,
        ce0 => conn_table_remote_ip_address_V_ce0,
        q0 => conn_table_remote_ip_address_V_q0,
        address1 => conn_table_remote_ip_address_V_address1,
        ce1 => conn_table_remote_ip_address_V_ce1,
        we1 => conn_table_remote_ip_address_V_we1,
        d1 => ifRequest_remote_ip_address_V_reg_382);

    conn_table_remote_udp_port_V_U : component rocev2_top_QPContext_table_0_s_conn_table_remote_udp_port_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conn_table_remote_udp_port_V_address0,
        ce0 => conn_table_remote_udp_port_V_ce0,
        q0 => conn_table_remote_udp_port_V_q0,
        address1 => conn_table_remote_udp_port_V_address1,
        ce1 => conn_table_remote_udp_port_V_ce1,
        we1 => conn_table_remote_udp_port_V_we1,
        d1 => ifRequest_remote_udp_port_V_reg_387);

    QPC_table_cq_id_V_U : component rocev2_top_QPContext_table_0_s_conn_table_remote_udp_port_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 500,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => QPC_table_cq_id_V_address0,
        ce0 => QPC_table_cq_id_V_ce0,
        q0 => QPC_table_cq_id_V_q0,
        address1 => QPC_table_cq_id_V_address1,
        ce1 => QPC_table_cq_id_V_ce1,
        we1 => QPC_table_cq_id_V_we1,
        d1 => cqidUpd_cq_id_V_reg_406);

    regslice_both_s_axis_qp_conn_interface_U : component rocev2_top_regslice_both
    generic map (
        DataWidth => 184)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_qp_conn_interface_TDATA,
        vld_in => s_axis_qp_conn_interface_TVALID,
        ack_in => regslice_both_s_axis_qp_conn_interface_U_ack_in,
        data_out => s_axis_qp_conn_interface_TDATA_int_regslice,
        vld_out => s_axis_qp_conn_interface_TVALID_int_regslice,
        ack_out => s_axis_qp_conn_interface_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_qp_conn_interface_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_386_i_reg_416 = ap_const_lv1_1) and (tmp_i_2644_reg_397_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter2_reg = ap_const_lv1_0))) then
                conn_table_remote_ip_address_V_load_reg_454 <= conn_table_remote_ip_address_V_q0;
                conn_table_remote_udp_port_V_load_reg_459 <= conn_table_remote_udp_port_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2644_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_i_reg_373 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cqidUpd_cq_id_V_reg_406 <= qpif2QPC_upd_dout(47 downto 32);
                cqidUpd_local_qpn_V_reg_401 <= cqidUpd_local_qpn_V_fu_308_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ifRequest_qpn_V_reg_377 <= ifRequest_qpn_V_fu_274_p1;
                ifRequest_remote_ip_address_V_reg_382 <= s_axis_qp_conn_interface_TDATA_int_regslice(167 downto 40);
                ifRequest_remote_qpn_V_reg_392 <= s_axis_qp_conn_interface_TDATA_int_regslice(39 downto 16);
                ifRequest_remote_udp_port_V_reg_387 <= s_axis_qp_conn_interface_TDATA_int_regslice(183 downto 168);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ifRequest_remote_qpn_V_reg_392_pp0_iter1_reg <= ifRequest_remote_qpn_V_reg_392;
                tmp_i_reg_373 <= tmp_i_nbreadreq_fu_96_p3;
                tmp_i_reg_373_pp0_iter1_reg <= tmp_i_reg_373;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2644_reg_397 = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_386_i_reg_416 <= tmp_386_i_nbreadreq_fu_124_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                tmp_386_i_reg_416_pp0_iter3_reg <= tmp_386_i_reg_416;
                tmp_i_2644_reg_397_pp0_iter2_reg <= tmp_i_2644_reg_397;
                tmp_i_2644_reg_397_pp0_iter3_reg <= tmp_i_2644_reg_397_pp0_iter2_reg;
                tmp_i_reg_373_pp0_iter2_reg <= tmp_i_reg_373_pp0_iter1_reg;
                tmp_i_reg_373_pp0_iter3_reg <= tmp_i_reg_373_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_386_i_reg_416 = ap_const_lv1_0) and (tmp_i_2644_reg_397_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter2_reg = ap_const_lv1_0))) then
                tmp_387_i_reg_435 <= tmp_387_i_nbreadreq_fu_138_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_373 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_2644_reg_397 <= tmp_i_2644_nbreadreq_fu_110_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_386_i_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (tmp_i_2644_reg_397 = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    zext_ln541_14_reg_420(15 downto 0) <= zext_ln541_14_fu_327_p1(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_reg_373 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    zext_ln541_reg_411(15 downto 0) <= zext_ln541_fu_322_p1(15 downto 0);
            end if;
        end if;
    end process;
    zext_ln541_reg_411(63 downto 16) <= "000000000000000000000000000000000000000000000000";
    zext_ln541_14_reg_420(63 downto 16) <= "000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    QPC_table_cq_id_V_address0 <= zext_ln541_15_fu_337_p1(9 - 1 downto 0);
    QPC_table_cq_id_V_address1 <= zext_ln541_13_fu_333_p1(9 - 1 downto 0);

    QPC_table_cq_id_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            QPC_table_cq_id_V_ce0 <= ap_const_logic_1;
        else 
            QPC_table_cq_id_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    QPC_table_cq_id_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            QPC_table_cq_id_V_ce1 <= ap_const_logic_1;
        else 
            QPC_table_cq_id_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    QPC_table_cq_id_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_373_pp0_iter1_reg, tmp_i_2644_reg_397, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_2644_reg_397 = ap_const_lv1_1) and (tmp_i_reg_373_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            QPC_table_cq_id_V_we1 <= ap_const_logic_1;
        else 
            QPC_table_cq_id_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, tmp_i_nbreadreq_fu_96_p3, ap_done_reg, qpif2QPC_upd_empty_n, ap_predicate_op43_read_state2, tx_ibhconnTable_req_empty_n, ap_predicate_op54_read_state3, wqecqe2connTable_req_empty_n, ap_predicate_op69_read_state4, connTable2wqecqe_rsp_full_n, ap_predicate_op83_write_state5, tx_connTable2ibh_rsp_full_n, ap_predicate_op88_write_state5, s_axis_qp_conn_interface_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((wqecqe2connTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1)) or ((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (tx_ibhconnTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op43_read_state2 = ap_const_boolean_1) and (qpif2QPC_upd_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (s_axis_qp_conn_interface_TVALID_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (((ap_predicate_op88_write_state5 = ap_const_boolean_1) and (tx_connTable2ibh_rsp_full_n = ap_const_logic_0)) or ((ap_predicate_op83_write_state5 = ap_const_boolean_1) and (connTable2wqecqe_rsp_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, tmp_i_nbreadreq_fu_96_p3, ap_done_reg, qpif2QPC_upd_empty_n, ap_predicate_op43_read_state2, tx_ibhconnTable_req_empty_n, ap_predicate_op54_read_state3, wqecqe2connTable_req_empty_n, ap_predicate_op69_read_state4, connTable2wqecqe_rsp_full_n, ap_predicate_op83_write_state5, tx_connTable2ibh_rsp_full_n, ap_predicate_op88_write_state5, s_axis_qp_conn_interface_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((wqecqe2connTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1)) or ((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (tx_ibhconnTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op43_read_state2 = ap_const_boolean_1) and (qpif2QPC_upd_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (s_axis_qp_conn_interface_TVALID_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (((ap_predicate_op88_write_state5 = ap_const_boolean_1) and (tx_connTable2ibh_rsp_full_n = ap_const_logic_0)) or ((ap_predicate_op83_write_state5 = ap_const_boolean_1) and (connTable2wqecqe_rsp_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, tmp_i_nbreadreq_fu_96_p3, ap_done_reg, qpif2QPC_upd_empty_n, ap_predicate_op43_read_state2, tx_ibhconnTable_req_empty_n, ap_predicate_op54_read_state3, wqecqe2connTable_req_empty_n, ap_predicate_op69_read_state4, connTable2wqecqe_rsp_full_n, ap_predicate_op83_write_state5, tx_connTable2ibh_rsp_full_n, ap_predicate_op88_write_state5, s_axis_qp_conn_interface_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((wqecqe2connTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1)) or ((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (tx_ibhconnTable_req_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op43_read_state2 = ap_const_boolean_1) and (qpif2QPC_upd_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (s_axis_qp_conn_interface_TVALID_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (((ap_predicate_op88_write_state5 = ap_const_boolean_1) and (tx_connTable2ibh_rsp_full_n = ap_const_logic_0)) or ((ap_predicate_op83_write_state5 = ap_const_boolean_1) and (connTable2wqecqe_rsp_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(tmp_i_nbreadreq_fu_96_p3, ap_done_reg, s_axis_qp_conn_interface_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (s_axis_qp_conn_interface_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(qpif2QPC_upd_empty_n, ap_predicate_op43_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op43_read_state2 = ap_const_boolean_1) and (qpif2QPC_upd_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(tx_ibhconnTable_req_empty_n, ap_predicate_op54_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (tx_ibhconnTable_req_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(wqecqe2connTable_req_empty_n, ap_predicate_op69_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((wqecqe2connTable_req_empty_n = ap_const_logic_0) and (ap_predicate_op69_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(connTable2wqecqe_rsp_full_n, ap_predicate_op83_write_state5, tx_connTable2ibh_rsp_full_n, ap_predicate_op88_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (((ap_predicate_op88_write_state5 = ap_const_boolean_1) and (tx_connTable2ibh_rsp_full_n = ap_const_logic_0)) or ((ap_predicate_op83_write_state5 = ap_const_boolean_1) and (connTable2wqecqe_rsp_full_n = ap_const_logic_0)));
    end process;


    ap_condition_430_assign_proc : process(ap_enable_reg_pp0_iter3, tmp_i_reg_373_pp0_iter2_reg, tmp_i_2644_reg_397_pp0_iter2_reg, ap_block_pp0_stage0)
    begin
                ap_condition_430 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_i_2644_reg_397_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter4, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op43_read_state2_assign_proc : process(tmp_i_reg_373, tmp_i_2644_nbreadreq_fu_110_p3)
    begin
                ap_predicate_op43_read_state2 <= ((tmp_i_2644_nbreadreq_fu_110_p3 = ap_const_lv1_1) and (tmp_i_reg_373 = ap_const_lv1_0));
    end process;


    ap_predicate_op54_read_state3_assign_proc : process(tmp_i_reg_373_pp0_iter1_reg, tmp_i_2644_reg_397, tmp_386_i_nbreadreq_fu_124_p3)
    begin
                ap_predicate_op54_read_state3 <= ((tmp_386_i_nbreadreq_fu_124_p3 = ap_const_lv1_1) and (tmp_i_2644_reg_397 = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op69_read_state4_assign_proc : process(tmp_i_reg_373_pp0_iter2_reg, tmp_i_2644_reg_397_pp0_iter2_reg, tmp_386_i_reg_416, tmp_387_i_nbreadreq_fu_138_p3)
    begin
                ap_predicate_op69_read_state4 <= ((tmp_387_i_nbreadreq_fu_138_p3 = ap_const_lv1_1) and (tmp_386_i_reg_416 = ap_const_lv1_0) and (tmp_i_2644_reg_397_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op83_write_state5_assign_proc : process(tmp_i_reg_373_pp0_iter3_reg, tmp_i_2644_reg_397_pp0_iter3_reg, tmp_386_i_reg_416_pp0_iter3_reg, tmp_387_i_reg_435)
    begin
                ap_predicate_op83_write_state5 <= ((tmp_387_i_reg_435 = ap_const_lv1_1) and (tmp_386_i_reg_416_pp0_iter3_reg = ap_const_lv1_0) and (tmp_i_2644_reg_397_pp0_iter3_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op88_write_state5_assign_proc : process(tmp_i_reg_373_pp0_iter3_reg, tmp_i_2644_reg_397_pp0_iter3_reg, tmp_386_i_reg_416_pp0_iter3_reg)
    begin
                ap_predicate_op88_write_state5 <= ((tmp_386_i_reg_416_pp0_iter3_reg = ap_const_lv1_1) and (tmp_i_2644_reg_397_pp0_iter3_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    connTable2wqecqe_rsp_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, connTable2wqecqe_rsp_full_n, ap_predicate_op83_write_state5, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op83_write_state5 = ap_const_boolean_1))) then 
            connTable2wqecqe_rsp_blk_n <= connTable2wqecqe_rsp_full_n;
        else 
            connTable2wqecqe_rsp_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    connTable2wqecqe_rsp_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_500_i_fu_343_p4),64));

    connTable2wqecqe_rsp_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op83_write_state5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op83_write_state5 = ap_const_boolean_1))) then 
            connTable2wqecqe_rsp_write <= ap_const_logic_1;
        else 
            connTable2wqecqe_rsp_write <= ap_const_logic_0;
        end if; 
    end process;

    conn_table_remote_ip_address_V_address0 <= zext_ln541_14_fu_327_p1(9 - 1 downto 0);
    conn_table_remote_ip_address_V_address1 <= zext_ln541_fu_322_p1(9 - 1 downto 0);

    conn_table_remote_ip_address_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_ip_address_V_ce0 <= ap_const_logic_1;
        else 
            conn_table_remote_ip_address_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_ip_address_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_ip_address_V_ce1 <= ap_const_logic_1;
        else 
            conn_table_remote_ip_address_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_ip_address_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_i_reg_373, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_reg_373 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_ip_address_V_we1 <= ap_const_logic_1;
        else 
            conn_table_remote_ip_address_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_qpn_V_address0_assign_proc : process(tmp_386_i_reg_416, tmp_387_i_nbreadreq_fu_138_p3, zext_ln541_14_reg_420, zext_ln541_15_fu_337_p1, ap_condition_430)
    begin
        if ((ap_const_boolean_1 = ap_condition_430)) then
            if ((tmp_386_i_reg_416 = ap_const_lv1_1)) then 
                conn_table_remote_qpn_V_address0 <= zext_ln541_14_reg_420(9 - 1 downto 0);
            elsif (((tmp_387_i_nbreadreq_fu_138_p3 = ap_const_lv1_1) and (tmp_386_i_reg_416 = ap_const_lv1_0))) then 
                conn_table_remote_qpn_V_address0 <= zext_ln541_15_fu_337_p1(9 - 1 downto 0);
            else 
                conn_table_remote_qpn_V_address0 <= "XXXXXXXXX";
            end if;
        else 
            conn_table_remote_qpn_V_address0 <= "XXXXXXXXX";
        end if; 
    end process;

    conn_table_remote_qpn_V_address1 <= zext_ln541_reg_411(9 - 1 downto 0);

    conn_table_remote_qpn_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, tmp_i_reg_373_pp0_iter2_reg, tmp_i_2644_reg_397_pp0_iter2_reg, tmp_386_i_reg_416, tmp_387_i_nbreadreq_fu_138_p3, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_386_i_reg_416 = ap_const_lv1_1) and (tmp_i_2644_reg_397_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter2_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_387_i_nbreadreq_fu_138_p3 = ap_const_lv1_1) and (tmp_386_i_reg_416 = ap_const_lv1_0) and (tmp_i_2644_reg_397_pp0_iter2_reg = ap_const_lv1_0) and (tmp_i_reg_373_pp0_iter2_reg = ap_const_lv1_0)))) then 
            conn_table_remote_qpn_V_ce0 <= ap_const_logic_1;
        else 
            conn_table_remote_qpn_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_qpn_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_qpn_V_ce1 <= ap_const_logic_1;
        else 
            conn_table_remote_qpn_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_qpn_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_reg_373_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_reg_373_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_qpn_V_we1 <= ap_const_logic_1;
        else 
            conn_table_remote_qpn_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    conn_table_remote_udp_port_V_address0 <= zext_ln541_14_fu_327_p1(9 - 1 downto 0);
    conn_table_remote_udp_port_V_address1 <= zext_ln541_fu_322_p1(9 - 1 downto 0);

    conn_table_remote_udp_port_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_udp_port_V_ce0 <= ap_const_logic_1;
        else 
            conn_table_remote_udp_port_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_udp_port_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_udp_port_V_ce1 <= ap_const_logic_1;
        else 
            conn_table_remote_udp_port_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conn_table_remote_udp_port_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_i_reg_373, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_reg_373 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conn_table_remote_udp_port_V_we1 <= ap_const_logic_1;
        else 
            conn_table_remote_udp_port_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cqidUpd_local_qpn_V_fu_308_p1 <= qpif2QPC_upd_dout(9 - 1 downto 0);
    ifRequest_qpn_V_fu_274_p1 <= s_axis_qp_conn_interface_TDATA_int_regslice(16 - 1 downto 0);

    qpif2QPC_upd_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, qpif2QPC_upd_empty_n, ap_predicate_op43_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op43_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            qpif2QPC_upd_blk_n <= qpif2QPC_upd_empty_n;
        else 
            qpif2QPC_upd_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    qpif2QPC_upd_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op43_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op43_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qpif2QPC_upd_read <= ap_const_logic_1;
        else 
            qpif2QPC_upd_read <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_qp_conn_interface_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_96_p3, ap_done_reg, ap_block_pp0_stage0, s_axis_qp_conn_interface_TVALID_int_regslice)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            s_axis_qp_conn_interface_TDATA_blk_n <= s_axis_qp_conn_interface_TVALID_int_regslice;
        else 
            s_axis_qp_conn_interface_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_qp_conn_interface_TREADY <= regslice_both_s_axis_qp_conn_interface_U_ack_in;

    s_axis_qp_conn_interface_TREADY_int_regslice_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_i_nbreadreq_fu_96_p3, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_i_nbreadreq_fu_96_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_qp_conn_interface_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_qp_conn_interface_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_386_i_nbreadreq_fu_124_p3 <= (0=>(tx_ibhconnTable_req_empty_n), others=>'-');
    tmp_387_i_nbreadreq_fu_138_p3 <= (0=>(wqecqe2connTable_req_empty_n), others=>'-');
    tmp_499_i_fu_358_p5 <= (((conn_table_remote_udp_port_V_load_reg_459 & conn_table_remote_ip_address_V_load_reg_454) & ap_const_lv104_0) & conn_table_remote_qpn_V_q0);
    tmp_500_i_fu_343_p4 <= ((QPC_table_cq_id_V_q0 & ap_const_lv8_0) & conn_table_remote_qpn_V_q0);
    tmp_i_2644_nbreadreq_fu_110_p3 <= (0=>(qpif2QPC_upd_empty_n), others=>'-');
    tmp_i_nbreadreq_fu_96_p3 <= (0=>(s_axis_qp_conn_interface_TVALID_int_regslice), others=>'-');

    tx_connTable2ibh_rsp_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, tx_connTable2ibh_rsp_full_n, ap_predicate_op88_write_state5, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op88_write_state5 = ap_const_boolean_1))) then 
            tx_connTable2ibh_rsp_blk_n <= tx_connTable2ibh_rsp_full_n;
        else 
            tx_connTable2ibh_rsp_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tx_connTable2ibh_rsp_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_499_i_fu_358_p5),384));

    tx_connTable2ibh_rsp_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op88_write_state5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op88_write_state5 = ap_const_boolean_1))) then 
            tx_connTable2ibh_rsp_write <= ap_const_logic_1;
        else 
            tx_connTable2ibh_rsp_write <= ap_const_logic_0;
        end if; 
    end process;


    tx_ibhconnTable_req_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, tx_ibhconnTable_req_empty_n, ap_predicate_op54_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            tx_ibhconnTable_req_blk_n <= tx_ibhconnTable_req_empty_n;
        else 
            tx_ibhconnTable_req_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_ibhconnTable_req_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op54_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            tx_ibhconnTable_req_read <= ap_const_logic_1;
        else 
            tx_ibhconnTable_req_read <= ap_const_logic_0;
        end if; 
    end process;


    wqecqe2connTable_req_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, wqecqe2connTable_req_empty_n, ap_predicate_op69_read_state4, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op69_read_state4 = ap_const_boolean_1))) then 
            wqecqe2connTable_req_blk_n <= wqecqe2connTable_req_empty_n;
        else 
            wqecqe2connTable_req_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wqecqe2connTable_req_read_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op69_read_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op69_read_state4 = ap_const_boolean_1))) then 
            wqecqe2connTable_req_read <= ap_const_logic_1;
        else 
            wqecqe2connTable_req_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln541_13_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cqidUpd_local_qpn_V_reg_401),64));
    zext_ln541_14_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tx_ibhconnTable_req_dout),64));
    zext_ln541_15_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(wqecqe2connTable_req_dout),64));
    zext_ln541_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ifRequest_qpn_V_reg_377),64));
end behav;
