-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_qp_interface_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_qp_interface_TVALID : IN STD_LOGIC;
    stateTable2qpi_rsp_dout : IN STD_LOGIC_VECTOR (122 downto 0);
    stateTable2qpi_rsp_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    stateTable2qpi_rsp_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    stateTable2qpi_rsp_empty_n : IN STD_LOGIC;
    stateTable2qpi_rsp_read : OUT STD_LOGIC;
    qpif2CQC_upd_din : OUT STD_LOGIC_VECTOR (191 downto 0);
    qpif2CQC_upd_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2CQC_upd_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2CQC_upd_full_n : IN STD_LOGIC;
    qpif2CQC_upd_write : OUT STD_LOGIC;
    qpif2QPC_upd_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    qpif2QPC_upd_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2QPC_upd_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2QPC_upd_full_n : IN STD_LOGIC;
    qpif2QPC_upd_write : OUT STD_LOGIC;
    qpi2stateTable_upd_req_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    qpi2stateTable_upd_req_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    qpi2stateTable_upd_req_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    qpi2stateTable_upd_req_full_n : IN STD_LOGIC;
    qpi2stateTable_upd_req_write : OUT STD_LOGIC;
    if2msnTable_init_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    if2msnTable_init_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    if2msnTable_init_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    if2msnTable_init_full_n : IN STD_LOGIC;
    if2msnTable_init_write : OUT STD_LOGIC;
    qpif2retransPointerInit_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    qpif2retransPointerInit_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2retransPointerInit_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2retransPointerInit_full_n : IN STD_LOGIC;
    qpif2retransPointerInit_write : OUT STD_LOGIC;
    qpif2wqePointerInit_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    qpif2wqePointerInit_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2wqePointerInit_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    qpif2wqePointerInit_full_n : IN STD_LOGIC;
    qpif2wqePointerInit_write : OUT STD_LOGIC;
    s_axis_qp_interface_TDATA : IN STD_LOGIC_VECTOR (207 downto 0);
    s_axis_qp_interface_TREADY : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_qp_interface_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_C2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000010";
    constant ap_const_lv32_C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001001";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_71 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110001";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_C1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv25_1000000 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_120_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op37_read_state1 : BOOLEAN;
    signal tmp_i_290_nbreadreq_fu_134_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op55_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal qp_fsmState_load_reg_395 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_399 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op60_write_state2 : BOOLEAN;
    signal ap_predicate_op63_write_state2 : BOOLEAN;
    signal ap_predicate_op66_write_state2 : BOOLEAN;
    signal tmp_i_290_reg_433 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op74_write_state2 : BOOLEAN;
    signal ap_predicate_op75_write_state2 : BOOLEAN;
    signal ap_predicate_op76_write_state2 : BOOLEAN;
    signal ap_predicate_op77_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal qp_fsmState : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal context_newState : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal context_qp_num_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal context_remote_psn_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal context_local_psn_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal s_axis_qp_interface_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal qpif2CQC_upd_blk_n : STD_LOGIC;
    signal qpif2QPC_upd_blk_n : STD_LOGIC;
    signal qpi2stateTable_upd_req_blk_n : STD_LOGIC;
    signal stateTable2qpi_rsp_blk_n : STD_LOGIC;
    signal if2msnTable_init_blk_n : STD_LOGIC;
    signal qpif2retransPointerInit_blk_n : STD_LOGIC;
    signal qpif2wqePointerInit_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln2635_9_reg_403 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln2635_2_reg_408 : STD_LOGIC_VECTOR (15 downto 0);
    signal qpn_V_reg_413 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln_i_reg_418 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_reg_423 : STD_LOGIC_VECTOR (73 downto 0);
    signal tmp_s_reg_428 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln2635_fu_194_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln2638_fu_352_p1 : STD_LOGIC_VECTOR (96 downto 0);
    signal p_08_fu_380_p6 : STD_LOGIC_VECTOR (96 downto 0);
    signal trunc_ln186_fu_363_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln2636_cast_fu_314_p7 : STD_LOGIC_VECTOR (176 downto 0);
    signal tmp_259_i_fu_332_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal or_ln_i_fu_345_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_s_axis_qp_interface_U_apdone_blk : STD_LOGIC;
    signal s_axis_qp_interface_TDATA_int_regslice : STD_LOGIC_VECTOR (207 downto 0);
    signal s_axis_qp_interface_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_qp_interface_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_qp_interface_U_ack_in : STD_LOGIC;
    signal ap_condition_207 : BOOLEAN;
    signal ap_condition_233 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rocev2_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_s_axis_qp_interface_U : component rocev2_top_regslice_both
    generic map (
        DataWidth => 208)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_qp_interface_TDATA,
        vld_in => s_axis_qp_interface_TVALID,
        ack_in => regslice_both_s_axis_qp_interface_U_ack_in,
        data_out => s_axis_qp_interface_TDATA_int_regslice,
        vld_out => s_axis_qp_interface_TVALID_int_regslice,
        ack_out => s_axis_qp_interface_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_qp_interface_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    qp_fsmState_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_207)) then
                if (((tmp_i_290_nbreadreq_fu_134_p3 = ap_const_lv1_1) and (qp_fsmState = ap_const_lv1_1))) then 
                    qp_fsmState <= ap_const_lv1_0;
                elsif (((tmp_i_nbreadreq_fu_120_p3 = ap_const_lv1_1) and (qp_fsmState = ap_const_lv1_0))) then 
                    qp_fsmState <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_120_p3 = ap_const_lv1_1) and (qp_fsmState = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                context_local_psn_V <= s_axis_qp_interface_TDATA_int_regslice(103 downto 80);
                context_newState <= trunc_ln2635_fu_194_p1;
                context_qp_num_V <= s_axis_qp_interface_TDATA_int_regslice(55 downto 32);
                context_remote_psn_V <= s_axis_qp_interface_TDATA_int_regslice(79 downto 56);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                qp_fsmState_load_reg_395 <= qp_fsmState;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_120_p3 = ap_const_lv1_1) and (qp_fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                qpn_V_reg_413 <= s_axis_qp_interface_TDATA_int_regslice(55 downto 32);
                tmp_reg_423 <= s_axis_qp_interface_TDATA_int_regslice(193 downto 120);
                tmp_s_reg_428 <= s_axis_qp_interface_TDATA_int_regslice(47 downto 32);
                trunc_ln2635_2_reg_408 <= s_axis_qp_interface_TDATA_int_regslice(119 downto 104);
                trunc_ln2635_9_reg_403 <= s_axis_qp_interface_TDATA_int_regslice(201 downto 194);
                trunc_ln_i_reg_418 <= s_axis_qp_interface_TDATA_int_regslice(113 downto 104);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((qp_fsmState = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_290_reg_433 <= tmp_i_290_nbreadreq_fu_134_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((qp_fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_reg_399 <= tmp_i_nbreadreq_fu_120_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_predicate_op37_read_state1, stateTable2qpi_rsp_empty_n, ap_predicate_op55_read_state1, ap_done_reg, qpif2CQC_upd_full_n, ap_predicate_op60_write_state2, qpif2QPC_upd_full_n, ap_predicate_op63_write_state2, qpi2stateTable_upd_req_full_n, ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, if2msnTable_init_full_n, ap_predicate_op75_write_state2, qpif2retransPointerInit_full_n, ap_predicate_op76_write_state2, qpif2wqePointerInit_full_n, ap_predicate_op77_write_state2, s_axis_qp_interface_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op55_read_state1 = ap_const_boolean_1) and (stateTable2qpi_rsp_empty_n = ap_const_logic_0)) or ((ap_predicate_op37_read_state1 = ap_const_boolean_1) and (s_axis_qp_interface_TVALID_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op66_write_state2 = ap_const_boolean_1) and (qpi2stateTable_upd_req_full_n = ap_const_logic_0)) or ((qpi2stateTable_upd_req_full_n = ap_const_logic_0) and (ap_predicate_op74_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op63_write_state2 = ap_const_boolean_1) and (qpif2QPC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op60_write_state2 = ap_const_boolean_1) and (qpif2CQC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op77_write_state2 = ap_const_boolean_1) and (qpif2wqePointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op76_write_state2 = ap_const_boolean_1) and (qpif2retransPointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op75_write_state2 = ap_const_boolean_1) and (if2msnTable_init_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_predicate_op37_read_state1, stateTable2qpi_rsp_empty_n, ap_predicate_op55_read_state1, ap_done_reg, qpif2CQC_upd_full_n, ap_predicate_op60_write_state2, qpif2QPC_upd_full_n, ap_predicate_op63_write_state2, qpi2stateTable_upd_req_full_n, ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, if2msnTable_init_full_n, ap_predicate_op75_write_state2, qpif2retransPointerInit_full_n, ap_predicate_op76_write_state2, qpif2wqePointerInit_full_n, ap_predicate_op77_write_state2, s_axis_qp_interface_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op55_read_state1 = ap_const_boolean_1) and (stateTable2qpi_rsp_empty_n = ap_const_logic_0)) or ((ap_predicate_op37_read_state1 = ap_const_boolean_1) and (s_axis_qp_interface_TVALID_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op66_write_state2 = ap_const_boolean_1) and (qpi2stateTable_upd_req_full_n = ap_const_logic_0)) or ((qpi2stateTable_upd_req_full_n = ap_const_logic_0) and (ap_predicate_op74_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op63_write_state2 = ap_const_boolean_1) and (qpif2QPC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op60_write_state2 = ap_const_boolean_1) and (qpif2CQC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op77_write_state2 = ap_const_boolean_1) and (qpif2wqePointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op76_write_state2 = ap_const_boolean_1) and (qpif2retransPointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op75_write_state2 = ap_const_boolean_1) and (if2msnTable_init_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, ap_predicate_op37_read_state1, stateTable2qpi_rsp_empty_n, ap_predicate_op55_read_state1, ap_done_reg, qpif2CQC_upd_full_n, ap_predicate_op60_write_state2, qpif2QPC_upd_full_n, ap_predicate_op63_write_state2, qpi2stateTable_upd_req_full_n, ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, if2msnTable_init_full_n, ap_predicate_op75_write_state2, qpif2retransPointerInit_full_n, ap_predicate_op76_write_state2, qpif2wqePointerInit_full_n, ap_predicate_op77_write_state2, s_axis_qp_interface_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op55_read_state1 = ap_const_boolean_1) and (stateTable2qpi_rsp_empty_n = ap_const_logic_0)) or ((ap_predicate_op37_read_state1 = ap_const_boolean_1) and (s_axis_qp_interface_TVALID_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op66_write_state2 = ap_const_boolean_1) and (qpi2stateTable_upd_req_full_n = ap_const_logic_0)) or ((qpi2stateTable_upd_req_full_n = ap_const_logic_0) and (ap_predicate_op74_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op63_write_state2 = ap_const_boolean_1) and (qpif2QPC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op60_write_state2 = ap_const_boolean_1) and (qpif2CQC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op77_write_state2 = ap_const_boolean_1) and (qpif2wqePointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op76_write_state2 = ap_const_boolean_1) and (qpif2retransPointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op75_write_state2 = ap_const_boolean_1) and (if2msnTable_init_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_predicate_op37_read_state1, stateTable2qpi_rsp_empty_n, ap_predicate_op55_read_state1, ap_done_reg, s_axis_qp_interface_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op55_read_state1 = ap_const_boolean_1) and (stateTable2qpi_rsp_empty_n = ap_const_logic_0)) or ((ap_predicate_op37_read_state1 = ap_const_boolean_1) and (s_axis_qp_interface_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(qpif2CQC_upd_full_n, ap_predicate_op60_write_state2, qpif2QPC_upd_full_n, ap_predicate_op63_write_state2, qpi2stateTable_upd_req_full_n, ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, if2msnTable_init_full_n, ap_predicate_op75_write_state2, qpif2retransPointerInit_full_n, ap_predicate_op76_write_state2, qpif2wqePointerInit_full_n, ap_predicate_op77_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op66_write_state2 = ap_const_boolean_1) and (qpi2stateTable_upd_req_full_n = ap_const_logic_0)) or ((qpi2stateTable_upd_req_full_n = ap_const_logic_0) and (ap_predicate_op74_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op63_write_state2 = ap_const_boolean_1) and (qpif2QPC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op60_write_state2 = ap_const_boolean_1) and (qpif2CQC_upd_full_n = ap_const_logic_0)) or ((ap_predicate_op77_write_state2 = ap_const_boolean_1) and (qpif2wqePointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op76_write_state2 = ap_const_boolean_1) and (qpif2retransPointerInit_full_n = ap_const_logic_0)) or ((ap_predicate_op75_write_state2 = ap_const_boolean_1) and (if2msnTable_init_full_n = ap_const_logic_0)));
    end process;


    ap_condition_207_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_207 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_233_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_233 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op37_read_state1_assign_proc : process(tmp_i_nbreadreq_fu_120_p3, qp_fsmState)
    begin
                ap_predicate_op37_read_state1 <= ((tmp_i_nbreadreq_fu_120_p3 = ap_const_lv1_1) and (qp_fsmState = ap_const_lv1_0));
    end process;


    ap_predicate_op55_read_state1_assign_proc : process(tmp_i_290_nbreadreq_fu_134_p3, qp_fsmState)
    begin
                ap_predicate_op55_read_state1 <= ((tmp_i_290_nbreadreq_fu_134_p3 = ap_const_lv1_1) and (qp_fsmState = ap_const_lv1_1));
    end process;


    ap_predicate_op60_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_reg_399)
    begin
                ap_predicate_op60_write_state2 <= ((tmp_i_reg_399 = ap_const_lv1_1) and (qp_fsmState_load_reg_395 = ap_const_lv1_0));
    end process;


    ap_predicate_op63_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_reg_399)
    begin
                ap_predicate_op63_write_state2 <= ((tmp_i_reg_399 = ap_const_lv1_1) and (qp_fsmState_load_reg_395 = ap_const_lv1_0));
    end process;


    ap_predicate_op66_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_reg_399)
    begin
                ap_predicate_op66_write_state2 <= ((tmp_i_reg_399 = ap_const_lv1_1) and (qp_fsmState_load_reg_395 = ap_const_lv1_0));
    end process;


    ap_predicate_op74_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_290_reg_433)
    begin
                ap_predicate_op74_write_state2 <= ((qp_fsmState_load_reg_395 = ap_const_lv1_1) and (tmp_i_290_reg_433 = ap_const_lv1_1));
    end process;


    ap_predicate_op75_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_290_reg_433)
    begin
                ap_predicate_op75_write_state2 <= ((qp_fsmState_load_reg_395 = ap_const_lv1_1) and (tmp_i_290_reg_433 = ap_const_lv1_1));
    end process;


    ap_predicate_op76_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_290_reg_433)
    begin
                ap_predicate_op76_write_state2 <= ((qp_fsmState_load_reg_395 = ap_const_lv1_1) and (tmp_i_290_reg_433 = ap_const_lv1_1));
    end process;


    ap_predicate_op77_write_state2_assign_proc : process(qp_fsmState_load_reg_395, tmp_i_290_reg_433)
    begin
                ap_predicate_op77_write_state2 <= ((qp_fsmState_load_reg_395 = ap_const_lv1_1) and (tmp_i_290_reg_433 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    if2msnTable_init_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, if2msnTable_init_full_n, ap_predicate_op75_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op75_write_state2 = ap_const_boolean_1))) then 
            if2msnTable_init_blk_n <= if2msnTable_init_full_n;
        else 
            if2msnTable_init_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    if2msnTable_init_din <= trunc_ln186_fu_363_p1;

    if2msnTable_init_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op75_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op75_write_state2 = ap_const_boolean_1))) then 
            if2msnTable_init_write <= ap_const_logic_1;
        else 
            if2msnTable_init_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln_i_fu_345_p3 <= (ap_const_lv1_0 & tmp_s_reg_428);
    p_08_fu_380_p6 <= ((((ap_const_lv1_1 & context_local_psn_V) & context_remote_psn_V) & context_newState) & trunc_ln186_fu_363_p1);

    qpi2stateTable_upd_req_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, qpi2stateTable_upd_req_full_n, ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_predicate_op66_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op74_write_state2 = ap_const_boolean_1)))) then 
            qpi2stateTable_upd_req_blk_n <= qpi2stateTable_upd_req_full_n;
        else 
            qpi2stateTable_upd_req_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    qpi2stateTable_upd_req_din_assign_proc : process(ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, zext_ln2638_fu_352_p1, p_08_fu_380_p6, ap_condition_233)
    begin
        if ((ap_const_boolean_1 = ap_condition_233)) then
            if ((ap_predicate_op74_write_state2 = ap_const_boolean_1)) then 
                qpi2stateTable_upd_req_din <= p_08_fu_380_p6;
            elsif ((ap_predicate_op66_write_state2 = ap_const_boolean_1)) then 
                qpi2stateTable_upd_req_din <= zext_ln2638_fu_352_p1;
            else 
                qpi2stateTable_upd_req_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            qpi2stateTable_upd_req_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    qpi2stateTable_upd_req_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op66_write_state2, ap_predicate_op74_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op66_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op74_write_state2 = ap_const_boolean_1)))) then 
            qpi2stateTable_upd_req_write <= ap_const_logic_1;
        else 
            qpi2stateTable_upd_req_write <= ap_const_logic_0;
        end if; 
    end process;


    qpif2CQC_upd_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, qpif2CQC_upd_full_n, ap_predicate_op60_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op60_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            qpif2CQC_upd_blk_n <= qpif2CQC_upd_full_n;
        else 
            qpif2CQC_upd_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    qpif2CQC_upd_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln2636_cast_fu_314_p7),192));

    qpif2CQC_upd_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op60_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op60_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qpif2CQC_upd_write <= ap_const_logic_1;
        else 
            qpif2CQC_upd_write <= ap_const_logic_0;
        end if; 
    end process;


    qpif2QPC_upd_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, qpif2QPC_upd_full_n, ap_predicate_op63_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op63_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            qpif2QPC_upd_blk_n <= qpif2QPC_upd_full_n;
        else 
            qpif2QPC_upd_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    qpif2QPC_upd_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_259_i_fu_332_p4),64));

    qpif2QPC_upd_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op63_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op63_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            qpif2QPC_upd_write <= ap_const_logic_1;
        else 
            qpif2QPC_upd_write <= ap_const_logic_0;
        end if; 
    end process;


    qpif2retransPointerInit_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, qpif2retransPointerInit_full_n, ap_predicate_op76_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op76_write_state2 = ap_const_boolean_1))) then 
            qpif2retransPointerInit_blk_n <= qpif2retransPointerInit_full_n;
        else 
            qpif2retransPointerInit_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    qpif2retransPointerInit_din <= context_qp_num_V;

    qpif2retransPointerInit_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op76_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op76_write_state2 = ap_const_boolean_1))) then 
            qpif2retransPointerInit_write <= ap_const_logic_1;
        else 
            qpif2retransPointerInit_write <= ap_const_logic_0;
        end if; 
    end process;


    qpif2wqePointerInit_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, qpif2wqePointerInit_full_n, ap_predicate_op77_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op77_write_state2 = ap_const_boolean_1))) then 
            qpif2wqePointerInit_blk_n <= qpif2wqePointerInit_full_n;
        else 
            qpif2wqePointerInit_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    qpif2wqePointerInit_din <= context_qp_num_V;

    qpif2wqePointerInit_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op77_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op77_write_state2 = ap_const_boolean_1))) then 
            qpif2wqePointerInit_write <= ap_const_logic_1;
        else 
            qpif2wqePointerInit_write <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_qp_interface_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op37_read_state1, ap_done_reg, ap_block_pp0_stage0, s_axis_qp_interface_TVALID_int_regslice)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op37_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            s_axis_qp_interface_TDATA_blk_n <= s_axis_qp_interface_TVALID_int_regslice;
        else 
            s_axis_qp_interface_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_qp_interface_TREADY <= regslice_both_s_axis_qp_interface_U_ack_in;

    s_axis_qp_interface_TREADY_int_regslice_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op37_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op37_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_qp_interface_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_qp_interface_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    stateTable2qpi_rsp_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, stateTable2qpi_rsp_empty_n, ap_predicate_op55_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op55_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            stateTable2qpi_rsp_blk_n <= stateTable2qpi_rsp_empty_n;
        else 
            stateTable2qpi_rsp_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stateTable2qpi_rsp_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op55_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op55_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            stateTable2qpi_rsp_read <= ap_const_logic_1;
        else 
            stateTable2qpi_rsp_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_259_i_fu_332_p4 <= ((trunc_ln2635_2_reg_408 & ap_const_lv8_0) & qpn_V_reg_413);
    tmp_i_290_nbreadreq_fu_134_p3 <= (0=>(stateTable2qpi_rsp_empty_n), others=>'-');
    tmp_i_nbreadreq_fu_120_p3 <= (0=>(s_axis_qp_interface_TVALID_int_regslice), others=>'-');
    trunc_ln186_fu_363_p1 <= context_qp_num_V(16 - 1 downto 0);
    trunc_ln2635_fu_194_p1 <= s_axis_qp_interface_TDATA_int_regslice(32 - 1 downto 0);
    zext_ln2636_cast_fu_314_p7 <= (((((ap_const_lv25_1000000 & trunc_ln2635_9_reg_403) & ap_const_lv6_0) & tmp_reg_423) & ap_const_lv54_0) & trunc_ln_i_reg_418);
    zext_ln2638_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_i_fu_345_p3),97));
end behav;
