-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_rx_exh_payload_512_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_pkgSplitTypeFifo_dout : IN STD_LOGIC_VECTOR (4 downto 0);
    rx_pkgSplitTypeFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_pkgSplitTypeFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_pkgSplitTypeFifo_empty_n : IN STD_LOGIC;
    rx_pkgSplitTypeFifo_read : OUT STD_LOGIC;
    rx_ibhDrop2exhFifo_dout : IN STD_LOGIC_VECTOR (1023 downto 0);
    rx_ibhDrop2exhFifo_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    rx_ibhDrop2exhFifo_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    rx_ibhDrop2exhFifo_empty_n : IN STD_LOGIC;
    rx_ibhDrop2exhFifo_read : OUT STD_LOGIC;
    rx_exh2aethShiftFifo_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    rx_exh2aethShiftFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exh2aethShiftFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exh2aethShiftFifo_full_n : IN STD_LOGIC;
    rx_exh2aethShiftFifo_write : OUT STD_LOGIC;
    rx_exh2rethShiftFifo_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    rx_exh2rethShiftFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exh2rethShiftFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exh2rethShiftFifo_full_n : IN STD_LOGIC;
    rx_exh2rethShiftFifo_write : OUT STD_LOGIC;
    rx_exhNoShiftFifo_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    rx_exhNoShiftFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exhNoShiftFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    rx_exhNoShiftFifo_full_n : IN STD_LOGIC;
    rx_exhNoShiftFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_rx_exh_payload_512_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_58_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op28_read_state1 : BOOLEAN;
    signal tmp_i_178_nbreadreq_fu_72_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op35_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal rep_state_load_reg_141 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_178_reg_148 : STD_LOGIC_VECTOR (0 downto 0);
    signal code_V_reg_162 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_predicate_op45_write_state2 : BOOLEAN;
    signal ap_predicate_op47_write_state2 : BOOLEAN;
    signal ap_predicate_op49_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal rep_state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal meta_op_code_V_1 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal rx_pkgSplitTypeFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_ibhDrop2exhFifo_blk_n : STD_LOGIC;
    signal rx_exh2rethShiftFifo_blk_n : STD_LOGIC;
    signal rx_exh2aethShiftFifo_blk_n : STD_LOGIC;
    signal rx_exhNoShiftFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal rx_ibhDrop2exhFifo_read_reg_152 : STD_LOGIC_VECTOR (1023 downto 0);
    signal currWord_last_V_fu_123_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_188 : BOOLEAN;
    signal ap_condition_184 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    rep_state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if ((ap_const_boolean_1 = ap_condition_188)) then 
                    rep_state <= ap_const_lv1_0;
                elsif (((tmp_i_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (rep_state = ap_const_lv1_0))) then 
                    rep_state <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_178_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (rep_state = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                code_V_reg_162 <= meta_op_code_V_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (rep_state = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                meta_op_code_V_1 <= rx_pkgSplitTypeFifo_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rep_state_load_reg_141 <= rep_state;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op35_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rx_ibhDrop2exhFifo_read_reg_152 <= rx_ibhDrop2exhFifo_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((rep_state = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_178_reg_148 <= tmp_i_178_nbreadreq_fu_72_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_pkgSplitTypeFifo_empty_n, ap_predicate_op28_read_state1, rx_ibhDrop2exhFifo_empty_n, ap_predicate_op35_read_state1, ap_done_reg, rx_exh2aethShiftFifo_full_n, ap_predicate_op45_write_state2, rx_exh2rethShiftFifo_full_n, ap_predicate_op47_write_state2, rx_exhNoShiftFifo_full_n, ap_predicate_op49_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op35_read_state1 = ap_const_boolean_1) and (rx_ibhDrop2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op28_read_state1 = ap_const_boolean_1) and (rx_pkgSplitTypeFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op45_write_state2 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op49_write_state2 = ap_const_boolean_1) and (rx_exhNoShiftFifo_full_n = ap_const_logic_0)) or ((rx_exh2rethShiftFifo_full_n = ap_const_logic_0) and (ap_predicate_op47_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_pkgSplitTypeFifo_empty_n, ap_predicate_op28_read_state1, rx_ibhDrop2exhFifo_empty_n, ap_predicate_op35_read_state1, ap_done_reg, rx_exh2aethShiftFifo_full_n, ap_predicate_op45_write_state2, rx_exh2rethShiftFifo_full_n, ap_predicate_op47_write_state2, rx_exhNoShiftFifo_full_n, ap_predicate_op49_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op35_read_state1 = ap_const_boolean_1) and (rx_ibhDrop2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op28_read_state1 = ap_const_boolean_1) and (rx_pkgSplitTypeFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op45_write_state2 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op49_write_state2 = ap_const_boolean_1) and (rx_exhNoShiftFifo_full_n = ap_const_logic_0)) or ((rx_exh2rethShiftFifo_full_n = ap_const_logic_0) and (ap_predicate_op47_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_pkgSplitTypeFifo_empty_n, ap_predicate_op28_read_state1, rx_ibhDrop2exhFifo_empty_n, ap_predicate_op35_read_state1, ap_done_reg, rx_exh2aethShiftFifo_full_n, ap_predicate_op45_write_state2, rx_exh2rethShiftFifo_full_n, ap_predicate_op47_write_state2, rx_exhNoShiftFifo_full_n, ap_predicate_op49_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op35_read_state1 = ap_const_boolean_1) and (rx_ibhDrop2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op28_read_state1 = ap_const_boolean_1) and (rx_pkgSplitTypeFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_predicate_op45_write_state2 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op49_write_state2 = ap_const_boolean_1) and (rx_exhNoShiftFifo_full_n = ap_const_logic_0)) or ((rx_exh2rethShiftFifo_full_n = ap_const_logic_0) and (ap_predicate_op47_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rx_pkgSplitTypeFifo_empty_n, ap_predicate_op28_read_state1, rx_ibhDrop2exhFifo_empty_n, ap_predicate_op35_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op35_read_state1 = ap_const_boolean_1) and (rx_ibhDrop2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op28_read_state1 = ap_const_boolean_1) and (rx_pkgSplitTypeFifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_exh2aethShiftFifo_full_n, ap_predicate_op45_write_state2, rx_exh2rethShiftFifo_full_n, ap_predicate_op47_write_state2, rx_exhNoShiftFifo_full_n, ap_predicate_op49_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op45_write_state2 = ap_const_boolean_1) and (rx_exh2aethShiftFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op49_write_state2 = ap_const_boolean_1) and (rx_exhNoShiftFifo_full_n = ap_const_logic_0)) or ((rx_exh2rethShiftFifo_full_n = ap_const_logic_0) and (ap_predicate_op47_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_184_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_184 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_188_assign_proc : process(tmp_i_178_nbreadreq_fu_72_p3, rep_state, currWord_last_V_fu_123_p3)
    begin
                ap_condition_188 <= ((tmp_i_178_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (rep_state = ap_const_lv1_1) and (currWord_last_V_fu_123_p3 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op28_read_state1_assign_proc : process(tmp_i_nbreadreq_fu_58_p3, rep_state)
    begin
                ap_predicate_op28_read_state1 <= ((tmp_i_nbreadreq_fu_58_p3 = ap_const_lv1_1) and (rep_state = ap_const_lv1_0));
    end process;


    ap_predicate_op35_read_state1_assign_proc : process(tmp_i_178_nbreadreq_fu_72_p3, rep_state)
    begin
                ap_predicate_op35_read_state1 <= ((tmp_i_178_nbreadreq_fu_72_p3 = ap_const_lv1_1) and (rep_state = ap_const_lv1_1));
    end process;


    ap_predicate_op45_write_state2_assign_proc : process(rep_state_load_reg_141, tmp_i_178_reg_148, code_V_reg_162)
    begin
                ap_predicate_op45_write_state2 <= ((((code_V_reg_162 = ap_const_lv5_F) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1)) or ((code_V_reg_162 = ap_const_lv5_D) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1))) or ((code_V_reg_162 = ap_const_lv5_10) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1)));
    end process;


    ap_predicate_op47_write_state2_assign_proc : process(rep_state_load_reg_141, tmp_i_178_reg_148, code_V_reg_162)
    begin
                ap_predicate_op47_write_state2 <= ((((code_V_reg_162 = ap_const_lv5_6) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1)) or ((code_V_reg_162 = ap_const_lv5_C) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1))) or ((code_V_reg_162 = ap_const_lv5_A) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1)));
    end process;


    ap_predicate_op49_write_state2_assign_proc : process(rep_state_load_reg_141, tmp_i_178_reg_148, code_V_reg_162)
    begin
                ap_predicate_op49_write_state2 <= (not((code_V_reg_162 = ap_const_lv5_10)) and not((code_V_reg_162 = ap_const_lv5_F)) and not((code_V_reg_162 = ap_const_lv5_D)) and not((code_V_reg_162 = ap_const_lv5_A)) and not((code_V_reg_162 = ap_const_lv5_6)) and not((code_V_reg_162 = ap_const_lv5_C)) and (tmp_i_178_reg_148 = ap_const_lv1_1) and (rep_state_load_reg_141 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    currWord_last_V_fu_123_p3 <= rx_ibhDrop2exhFifo_dout(576 downto 576);

    rx_exh2aethShiftFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_exh2aethShiftFifo_full_n, ap_predicate_op45_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op45_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_exh2aethShiftFifo_blk_n <= rx_exh2aethShiftFifo_full_n;
        else 
            rx_exh2aethShiftFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_exh2aethShiftFifo_din <= rx_ibhDrop2exhFifo_read_reg_152;

    rx_exh2aethShiftFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op45_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op45_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_exh2aethShiftFifo_write <= ap_const_logic_1;
        else 
            rx_exh2aethShiftFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_exh2rethShiftFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_exh2rethShiftFifo_full_n, ap_predicate_op47_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op47_write_state2 = ap_const_boolean_1))) then 
            rx_exh2rethShiftFifo_blk_n <= rx_exh2rethShiftFifo_full_n;
        else 
            rx_exh2rethShiftFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_exh2rethShiftFifo_din <= rx_ibhDrop2exhFifo_read_reg_152;

    rx_exh2rethShiftFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op47_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op47_write_state2 = ap_const_boolean_1))) then 
            rx_exh2rethShiftFifo_write <= ap_const_logic_1;
        else 
            rx_exh2rethShiftFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_exhNoShiftFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_exhNoShiftFifo_full_n, ap_predicate_op49_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op49_write_state2 = ap_const_boolean_1))) then 
            rx_exhNoShiftFifo_blk_n <= rx_exhNoShiftFifo_full_n;
        else 
            rx_exhNoShiftFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_exhNoShiftFifo_din <= rx_ibhDrop2exhFifo_read_reg_152;

    rx_exhNoShiftFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op49_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op49_write_state2 = ap_const_boolean_1))) then 
            rx_exhNoShiftFifo_write <= ap_const_logic_1;
        else 
            rx_exhNoShiftFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_ibhDrop2exhFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_ibhDrop2exhFifo_empty_n, ap_predicate_op35_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op35_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_ibhDrop2exhFifo_blk_n <= rx_ibhDrop2exhFifo_empty_n;
        else 
            rx_ibhDrop2exhFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_ibhDrop2exhFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op35_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op35_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_ibhDrop2exhFifo_read <= ap_const_logic_1;
        else 
            rx_ibhDrop2exhFifo_read <= ap_const_logic_0;
        end if; 
    end process;


    rx_pkgSplitTypeFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_pkgSplitTypeFifo_empty_n, ap_predicate_op28_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op28_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_pkgSplitTypeFifo_blk_n <= rx_pkgSplitTypeFifo_empty_n;
        else 
            rx_pkgSplitTypeFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_pkgSplitTypeFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op28_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op28_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_pkgSplitTypeFifo_read <= ap_const_logic_1;
        else 
            rx_pkgSplitTypeFifo_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_i_178_nbreadreq_fu_72_p3 <= (0=>(rx_ibhDrop2exhFifo_empty_n), others=>'-');
    tmp_i_nbreadreq_fu_58_p3 <= (0=>(rx_pkgSplitTypeFifo_empty_n), others=>'-');
end behav;
