-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rocev2_top_rx_process_exh_512_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_shift2exhFifo_dout : IN STD_LOGIC_VECTOR (1023 downto 0);
    rx_shift2exhFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_shift2exhFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_shift2exhFifo_empty_n : IN STD_LOGIC;
    rx_shift2exhFifo_read : OUT STD_LOGIC;
    rx_ibh2exh_MetaFifo_dout : IN STD_LOGIC_VECTOR (4 downto 0);
    rx_ibh2exh_MetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2exh_MetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_ibh2exh_MetaFifo_empty_n : IN STD_LOGIC;
    rx_ibh2exh_MetaFifo_read : OUT STD_LOGIC;
    rx_exhMetaFifo_din : OUT STD_LOGIC_VECTOR (24 downto 0);
    rx_exhMetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_exhMetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_exhMetaFifo_full_n : IN STD_LOGIC;
    rx_exhMetaFifo_write : OUT STD_LOGIC;
    rx_exh2drop_MetaFifo_din : OUT STD_LOGIC_VECTOR (144 downto 0);
    rx_exh2drop_MetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_exh2drop_MetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_exh2drop_MetaFifo_full_n : IN STD_LOGIC;
    rx_exh2drop_MetaFifo_write : OUT STD_LOGIC;
    rx_exh2dropFifo_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    rx_exh2dropFifo_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    rx_exh2dropFifo_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    rx_exh2dropFifo_full_n : IN STD_LOGIC;
    rx_exh2dropFifo_write : OUT STD_LOGIC );
end;


architecture behav of rocev2_top_rx_process_exh_512_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv25_2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_const_lv145_lc_3 : STD_LOGIC_VECTOR (144 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv33_FFF : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000111111111111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal grp_nbreadreq_fu_142_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op30_read_state1 : BOOLEAN;
    signal ap_predicate_op63_read_state1 : BOOLEAN;
    signal ap_predicate_op93_read_state1 : BOOLEAN;
    signal tmp_i_nbreadreq_fu_156_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op104_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal state_1_load_reg_734 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_i_reg_742 : STD_LOGIC_VECTOR (0 downto 0);
    signal metaWritten_1_load_reg_738 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_762 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op126_write_state2 : BOOLEAN;
    signal ap_predicate_op138_write_state2 : BOOLEAN;
    signal ap_predicate_op141_write_state2 : BOOLEAN;
    signal icmp_ln73_reg_766 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op143_write_state2 : BOOLEAN;
    signal tmp_i_176_reg_770 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1023_reg_790 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op146_write_state2 : BOOLEAN;
    signal ap_predicate_op152_write_state2 : BOOLEAN;
    signal ap_predicate_op155_write_state2 : BOOLEAN;
    signal tmp_17_i_reg_794 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op157_write_state2 : BOOLEAN;
    signal ap_predicate_op158_write_state2 : BOOLEAN;
    signal ap_predicate_op159_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal state_1 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal opCode_V : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal metaWritten_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ackHeader_ready : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ackHeader_idx : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ackHeader_header_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal rdmaHeader_ready : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal rdmaHeader_idx : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rdmaHeader_header_V : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal rx_ibh2exh_MetaFifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_shift2exhFifo_blk_n : STD_LOGIC;
    signal rx_exh2dropFifo_blk_n : STD_LOGIC;
    signal rx_exhMetaFifo_blk_n : STD_LOGIC;
    signal rx_exh2drop_MetaFifo_blk_n : STD_LOGIC;
    signal reg_327 : STD_LOGIC_VECTOR (1023 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal metaWritten_1_load_load_fu_340_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_356_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal rdmaHeader_ready_load_load_fu_344_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_427_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ackHeader_ready_load_load_fu_415_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1023_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_0_i_reg_193 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rdmaHeader_idx_new_0_i_phi_fu_207_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln67_1_fu_360_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_0_i_reg_204 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_1_i_reg_214 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_319_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_rdmaHeader_ready_new_1_i_reg_225 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_1_i_reg_236 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ackHeader_ready_flag_0_i_reg_247 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_ackHeader_idx_new_0_i_phi_fu_261_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln67_fu_431_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_ackHeader_idx_new_0_i_reg_258 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ackHeader_ready_flag_1_i_reg_268 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ackHeader_ready_new_1_i_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_ackHeader_idx_new_1_i_reg_290 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_p_Val2_9_reg_301 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter1_p_Val2_9_reg_301 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter0_p_Val2_10_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_p_Val2_10_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln80_1_fu_584_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln240_fu_678_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln211_fu_716_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_s_fu_683_p3 : STD_LOGIC_VECTOR (144 downto 0);
    signal zext_ln212_fu_729_p1 : STD_LOGIC_VECTOR (144 downto 0);
    signal add_ln73_fu_385_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln80_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_1_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_2_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_3_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_1_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_5_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_6_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_3_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_4_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_4_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_2_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_5_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln80_fu_570_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_i_fu_628_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_i_fu_618_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_i_fu_608_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_i_fu_598_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_638_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1495_fu_650_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_fu_654_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_fu_660_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln1_fu_670_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_23_i_fu_692_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1019_3_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln211_cast_fu_708_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln2_fu_721_p3 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_327 : BOOLEAN;
    signal ap_condition_298 : BOOLEAN;
    signal ap_condition_267 : BOOLEAN;
    signal ap_condition_305 : BOOLEAN;
    signal ap_condition_283 : BOOLEAN;
    signal ap_condition_393 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_p_Val2_10_reg_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_267)) then
                if ((ap_const_boolean_1 = ap_condition_298)) then 
                    ap_phi_reg_pp0_iter1_p_Val2_10_reg_310 <= tmp_12_fu_427_p1;
                elsif ((ap_const_boolean_1 = ap_condition_327)) then 
                    ap_phi_reg_pp0_iter1_p_Val2_10_reg_310 <= ackHeader_header_V;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_Val2_10_reg_310 <= ap_phi_reg_pp0_iter0_p_Val2_10_reg_310;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_Val2_9_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_267)) then
                if ((ap_const_boolean_1 = ap_condition_283)) then 
                    ap_phi_reg_pp0_iter1_p_Val2_9_reg_301 <= tmp_13_fu_356_p1;
                elsif ((ap_const_boolean_1 = ap_condition_305)) then 
                    ap_phi_reg_pp0_iter1_p_Val2_9_reg_301 <= rdmaHeader_header_V;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_Val2_9_reg_301 <= ap_phi_reg_pp0_iter0_p_Val2_9_reg_301;
                end if;
            end if; 
        end if;
    end process;

    metaWritten_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_156_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                metaWritten_1 <= ap_const_lv1_0;
            elsif ((((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_3) and (metaWritten_1_load_load_fu_340_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1) and (metaWritten_1_load_load_fu_340_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (metaWritten_1_load_load_fu_340_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                metaWritten_1 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    state_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_156_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                state_1 <= select_ln80_1_fu_584_p3;
            elsif ((((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_3) and (grp_fu_319_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1) and (grp_fu_319_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (grp_fu_319_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                state_1 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = ackHeader_ready_load_load_fu_415_p1) and (grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ackHeader_header_V <= tmp_12_fu_427_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1) and (ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ackHeader_idx <= ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4;
                ackHeader_ready <= ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (metaWritten_1_load_load_fu_340_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln1019_reg_762 <= icmp_ln1019_fu_373_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln1023_reg_790 <= icmp_ln1023_fu_444_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln73_reg_766 <= icmp_ln73_fu_391_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                metaWritten_1_load_reg_738 <= metaWritten_1;
                state_1_load_reg_734 <= state_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_nbreadreq_fu_156_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                opCode_V <= rx_ibh2exh_MetaFifo_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (rdmaHeader_ready_load_load_fu_344_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rdmaHeader_header_V <= tmp_13_fu_356_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                rdmaHeader_idx <= ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4;
                rdmaHeader_ready <= ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_predicate_op93_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op63_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op30_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_327 <= rx_shift2exhFifo_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_1 = ap_const_lv2_3) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_17_i_reg_794 <= grp_nbreadreq_fu_142_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_1 = ap_const_lv2_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_18_i_reg_742 <= grp_nbreadreq_fu_142_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_1 = ap_const_lv2_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_176_reg_770 <= grp_nbreadreq_fu_142_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ackHeader_ready_load_load_fu_415_p1 <= ackHeader_ready;
    add_ln67_1_fu_360_p2 <= std_logic_vector(unsigned(rdmaHeader_idx) + unsigned(ap_const_lv16_1));
    add_ln67_fu_431_p2 <= std_logic_vector(unsigned(ackHeader_idx) + unsigned(ap_const_lv16_1));
    add_ln73_fu_385_p2 <= std_logic_vector(unsigned(opCode_V) + unsigned(ap_const_lv5_1A));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_shift2exhFifo_empty_n, ap_predicate_op30_read_state1, ap_predicate_op63_read_state1, ap_predicate_op93_read_state1, rx_ibh2exh_MetaFifo_empty_n, ap_predicate_op104_read_state1, ap_done_reg, rx_exhMetaFifo_full_n, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, rx_exh2drop_MetaFifo_full_n, ap_predicate_op141_write_state2, rx_exh2dropFifo_full_n, ap_predicate_op143_write_state2, ap_predicate_op146_write_state2, ap_predicate_op152_write_state2, ap_predicate_op155_write_state2, ap_predicate_op157_write_state2, ap_predicate_op158_write_state2, ap_predicate_op159_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op104_read_state1 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op93_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op63_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op152_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op138_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op159_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op157_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op155_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op146_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op143_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op141_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_shift2exhFifo_empty_n, ap_predicate_op30_read_state1, ap_predicate_op63_read_state1, ap_predicate_op93_read_state1, rx_ibh2exh_MetaFifo_empty_n, ap_predicate_op104_read_state1, ap_done_reg, rx_exhMetaFifo_full_n, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, rx_exh2drop_MetaFifo_full_n, ap_predicate_op141_write_state2, rx_exh2dropFifo_full_n, ap_predicate_op143_write_state2, ap_predicate_op146_write_state2, ap_predicate_op152_write_state2, ap_predicate_op155_write_state2, ap_predicate_op157_write_state2, ap_predicate_op158_write_state2, ap_predicate_op159_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op104_read_state1 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op93_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op63_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op152_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op138_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op159_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op157_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op155_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op146_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op143_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op141_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, rx_shift2exhFifo_empty_n, ap_predicate_op30_read_state1, ap_predicate_op63_read_state1, ap_predicate_op93_read_state1, rx_ibh2exh_MetaFifo_empty_n, ap_predicate_op104_read_state1, ap_done_reg, rx_exhMetaFifo_full_n, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, rx_exh2drop_MetaFifo_full_n, ap_predicate_op141_write_state2, rx_exh2dropFifo_full_n, ap_predicate_op143_write_state2, ap_predicate_op146_write_state2, ap_predicate_op152_write_state2, ap_predicate_op155_write_state2, ap_predicate_op157_write_state2, ap_predicate_op158_write_state2, ap_predicate_op159_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op104_read_state1 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op93_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op63_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op152_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op138_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op159_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op157_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op155_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op146_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op143_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op141_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rx_shift2exhFifo_empty_n, ap_predicate_op30_read_state1, ap_predicate_op63_read_state1, ap_predicate_op93_read_state1, rx_ibh2exh_MetaFifo_empty_n, ap_predicate_op104_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_predicate_op104_read_state1 = ap_const_boolean_1) and (rx_ibh2exh_MetaFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op93_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op63_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)) or ((ap_predicate_op30_read_state1 = ap_const_boolean_1) and (rx_shift2exhFifo_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_exhMetaFifo_full_n, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, rx_exh2drop_MetaFifo_full_n, ap_predicate_op141_write_state2, rx_exh2dropFifo_full_n, ap_predicate_op143_write_state2, ap_predicate_op146_write_state2, ap_predicate_op152_write_state2, ap_predicate_op155_write_state2, ap_predicate_op157_write_state2, ap_predicate_op158_write_state2, ap_predicate_op159_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op152_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op138_write_state2 = ap_const_boolean_1)) or ((rx_exhMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)) or ((ap_predicate_op159_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op157_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op155_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op146_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op143_write_state2 = ap_const_boolean_1) and (rx_exh2dropFifo_full_n = ap_const_logic_0)) or ((ap_predicate_op141_write_state2 = ap_const_boolean_1) and (rx_exh2drop_MetaFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_267_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_267 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_283_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, rdmaHeader_ready_load_load_fu_344_p1)
    begin
                ap_condition_283 <= ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (rdmaHeader_ready_load_load_fu_344_p1 = ap_const_lv1_0));
    end process;


    ap_condition_298_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, ackHeader_ready_load_load_fu_415_p1)
    begin
                ap_condition_298 <= ((ap_const_lv1_0 = ackHeader_ready_load_load_fu_415_p1) and (grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1));
    end process;


    ap_condition_305_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, rdmaHeader_ready_load_load_fu_344_p1)
    begin
                ap_condition_305 <= ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (rdmaHeader_ready_load_load_fu_344_p1 = ap_const_lv1_1));
    end process;


    ap_condition_327_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, ackHeader_ready_load_load_fu_415_p1)
    begin
                ap_condition_327 <= ((ap_const_lv1_1 = ackHeader_ready_load_load_fu_415_p1) and (grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1));
    end process;


    ap_condition_393_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_393 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_ackHeader_idx_new_0_i_phi_fu_261_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, ackHeader_ready_load_load_fu_415_p1, add_ln67_fu_431_p2, ap_phi_reg_pp0_iter0_ackHeader_idx_new_0_i_reg_258)
    begin
        if (((ap_const_lv1_0 = ackHeader_ready_load_load_fu_415_p1) and (grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1))) then 
            ap_phi_mux_ackHeader_idx_new_0_i_phi_fu_261_p4 <= add_ln67_fu_431_p2;
        else 
            ap_phi_mux_ackHeader_idx_new_0_i_phi_fu_261_p4 <= ap_phi_reg_pp0_iter0_ackHeader_idx_new_0_i_reg_258;
        end if; 
    end process;


    ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, grp_fu_319_p3, ap_phi_mux_ackHeader_idx_new_0_i_phi_fu_261_p4, ap_phi_reg_pp0_iter0_ackHeader_idx_new_1_i_reg_290)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1))) then
            if ((grp_fu_319_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4 <= ap_phi_mux_ackHeader_idx_new_0_i_phi_fu_261_p4;
            elsif ((grp_fu_319_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4 <= ap_phi_reg_pp0_iter0_ackHeader_idx_new_1_i_reg_290;
            end if;
        else 
            ap_phi_mux_ackHeader_idx_new_1_i_phi_fu_293_p4 <= ap_phi_reg_pp0_iter0_ackHeader_idx_new_1_i_reg_290;
        end if; 
    end process;


    ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, ackHeader_ready_load_load_fu_415_p1, ap_phi_reg_pp0_iter0_ackHeader_ready_flag_0_i_reg_247)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1))) then
            if ((ap_const_lv1_0 = ackHeader_ready_load_load_fu_415_p1)) then 
                ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4 <= ap_const_lv1_1;
            elsif ((ap_const_lv1_1 = ackHeader_ready_load_load_fu_415_p1)) then 
                ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4 <= ap_phi_reg_pp0_iter0_ackHeader_ready_flag_0_i_reg_247;
            end if;
        else 
            ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4 <= ap_phi_reg_pp0_iter0_ackHeader_ready_flag_0_i_reg_247;
        end if; 
    end process;


    ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, grp_fu_319_p3, ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4, ap_phi_reg_pp0_iter0_ackHeader_ready_flag_1_i_reg_268)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1))) then
            if ((grp_fu_319_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4 <= ap_phi_mux_ackHeader_ready_flag_0_i_phi_fu_250_p4;
            elsif ((grp_fu_319_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4 <= ap_phi_reg_pp0_iter0_ackHeader_ready_flag_1_i_reg_268;
            end if;
        else 
            ap_phi_mux_ackHeader_ready_flag_1_i_phi_fu_271_p4 <= ap_phi_reg_pp0_iter0_ackHeader_ready_flag_1_i_reg_268;
        end if; 
    end process;


    ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, grp_fu_319_p3, ap_phi_reg_pp0_iter0_ackHeader_ready_new_1_i_reg_279)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1))) then
            if ((grp_fu_319_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4 <= ap_const_lv1_1;
            elsif ((grp_fu_319_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4 <= ap_phi_reg_pp0_iter0_ackHeader_ready_new_1_i_reg_279;
            end if;
        else 
            ap_phi_mux_ackHeader_ready_new_1_i_phi_fu_282_p4 <= ap_phi_reg_pp0_iter0_ackHeader_ready_new_1_i_reg_279;
        end if; 
    end process;


    ap_phi_mux_rdmaHeader_idx_new_0_i_phi_fu_207_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, rdmaHeader_ready_load_load_fu_344_p1, add_ln67_1_fu_360_p2, ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_0_i_reg_204)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2) and (rdmaHeader_ready_load_load_fu_344_p1 = ap_const_lv1_0))) then 
            ap_phi_mux_rdmaHeader_idx_new_0_i_phi_fu_207_p4 <= add_ln67_1_fu_360_p2;
        else 
            ap_phi_mux_rdmaHeader_idx_new_0_i_phi_fu_207_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_0_i_reg_204;
        end if; 
    end process;


    ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, ap_phi_mux_rdmaHeader_idx_new_0_i_phi_fu_207_p4, grp_fu_319_p3, ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_1_i_reg_236)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2))) then
            if ((grp_fu_319_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4 <= ap_phi_mux_rdmaHeader_idx_new_0_i_phi_fu_207_p4;
            elsif ((grp_fu_319_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_1_i_reg_236;
            end if;
        else 
            ap_phi_mux_rdmaHeader_idx_new_1_i_phi_fu_239_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_1_i_reg_236;
        end if; 
    end process;


    ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, rdmaHeader_ready_load_load_fu_344_p1, ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_0_i_reg_193)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2))) then
            if ((rdmaHeader_ready_load_load_fu_344_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4 <= ap_const_lv1_1;
            elsif ((rdmaHeader_ready_load_load_fu_344_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_0_i_reg_193;
            end if;
        else 
            ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_0_i_reg_193;
        end if; 
    end process;


    ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4, ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_1_i_reg_214, grp_fu_319_p3)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2))) then
            if ((grp_fu_319_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4 <= ap_phi_mux_rdmaHeader_ready_flag_0_i_phi_fu_196_p4;
            elsif ((grp_fu_319_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_1_i_reg_214;
            end if;
        else 
            ap_phi_mux_rdmaHeader_ready_flag_1_i_phi_fu_217_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_1_i_reg_214;
        end if; 
    end process;


    ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1, grp_fu_319_p3, ap_phi_reg_pp0_iter0_rdmaHeader_ready_new_1_i_reg_225)
    begin
        if (((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2))) then
            if ((grp_fu_319_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4 <= ap_const_lv1_1;
            elsif ((grp_fu_319_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_ready_new_1_i_reg_225;
            end if;
        else 
            ap_phi_mux_rdmaHeader_ready_new_1_i_phi_fu_228_p4 <= ap_phi_reg_pp0_iter0_rdmaHeader_ready_new_1_i_reg_225;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_ackHeader_idx_new_0_i_reg_258 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_ackHeader_idx_new_1_i_reg_290 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_ackHeader_ready_flag_0_i_reg_247 <= "X";
    ap_phi_reg_pp0_iter0_ackHeader_ready_flag_1_i_reg_268 <= "X";
    ap_phi_reg_pp0_iter0_ackHeader_ready_new_1_i_reg_279 <= "X";
    ap_phi_reg_pp0_iter0_p_Val2_10_reg_310 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_p_Val2_9_reg_301 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_0_i_reg_204 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_rdmaHeader_idx_new_1_i_reg_236 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_0_i_reg_193 <= "X";
    ap_phi_reg_pp0_iter0_rdmaHeader_ready_flag_1_i_reg_214 <= "X";
    ap_phi_reg_pp0_iter0_rdmaHeader_ready_new_1_i_reg_225 <= "X";

    ap_predicate_op104_read_state1_assign_proc : process(tmp_i_nbreadreq_fu_156_p3, state_1)
    begin
                ap_predicate_op104_read_state1 <= ((tmp_i_nbreadreq_fu_156_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_0));
    end process;


    ap_predicate_op126_write_state2_assign_proc : process(state_1_load_reg_734, tmp_18_i_reg_742, metaWritten_1_load_reg_738, icmp_ln1019_reg_762)
    begin
                ap_predicate_op126_write_state2 <= ((icmp_ln1019_reg_762 = ap_const_lv1_0) and (metaWritten_1_load_reg_738 = ap_const_lv1_0) and (tmp_18_i_reg_742 = ap_const_lv1_1) and (state_1_load_reg_734 = ap_const_lv2_2));
    end process;


    ap_predicate_op138_write_state2_assign_proc : process(state_1_load_reg_734, tmp_18_i_reg_742, metaWritten_1_load_reg_738, icmp_ln1019_reg_762)
    begin
                ap_predicate_op138_write_state2 <= ((icmp_ln1019_reg_762 = ap_const_lv1_1) and (metaWritten_1_load_reg_738 = ap_const_lv1_0) and (tmp_18_i_reg_742 = ap_const_lv1_1) and (state_1_load_reg_734 = ap_const_lv2_2));
    end process;


    ap_predicate_op141_write_state2_assign_proc : process(state_1_load_reg_734, tmp_18_i_reg_742, metaWritten_1_load_reg_738)
    begin
                ap_predicate_op141_write_state2 <= ((metaWritten_1_load_reg_738 = ap_const_lv1_0) and (tmp_18_i_reg_742 = ap_const_lv1_1) and (state_1_load_reg_734 = ap_const_lv2_2));
    end process;


    ap_predicate_op143_write_state2_assign_proc : process(state_1_load_reg_734, tmp_18_i_reg_742, icmp_ln73_reg_766)
    begin
                ap_predicate_op143_write_state2 <= ((tmp_18_i_reg_742 = ap_const_lv1_1) and (state_1_load_reg_734 = ap_const_lv2_2) and (icmp_ln73_reg_766 = ap_const_lv1_1));
    end process;


    ap_predicate_op146_write_state2_assign_proc : process(state_1_load_reg_734, tmp_i_176_reg_770, icmp_ln1023_reg_790)
    begin
                ap_predicate_op146_write_state2 <= ((state_1_load_reg_734 = ap_const_lv2_1) and (icmp_ln1023_reg_790 = ap_const_lv1_0) and (tmp_i_176_reg_770 = ap_const_lv1_1));
    end process;


    ap_predicate_op152_write_state2_assign_proc : process(state_1_load_reg_734, metaWritten_1_load_reg_738, tmp_i_176_reg_770)
    begin
                ap_predicate_op152_write_state2 <= ((metaWritten_1_load_reg_738 = ap_const_lv1_0) and (state_1_load_reg_734 = ap_const_lv2_1) and (tmp_i_176_reg_770 = ap_const_lv1_1));
    end process;


    ap_predicate_op155_write_state2_assign_proc : process(state_1_load_reg_734, metaWritten_1_load_reg_738, tmp_i_176_reg_770)
    begin
                ap_predicate_op155_write_state2 <= ((metaWritten_1_load_reg_738 = ap_const_lv1_0) and (state_1_load_reg_734 = ap_const_lv2_1) and (tmp_i_176_reg_770 = ap_const_lv1_1));
    end process;


    ap_predicate_op157_write_state2_assign_proc : process(state_1_load_reg_734, tmp_17_i_reg_794)
    begin
                ap_predicate_op157_write_state2 <= ((state_1_load_reg_734 = ap_const_lv2_3) and (tmp_17_i_reg_794 = ap_const_lv1_1));
    end process;


    ap_predicate_op158_write_state2_assign_proc : process(state_1_load_reg_734, metaWritten_1_load_reg_738, tmp_17_i_reg_794)
    begin
                ap_predicate_op158_write_state2 <= ((metaWritten_1_load_reg_738 = ap_const_lv1_0) and (state_1_load_reg_734 = ap_const_lv2_3) and (tmp_17_i_reg_794 = ap_const_lv1_1));
    end process;


    ap_predicate_op159_write_state2_assign_proc : process(state_1_load_reg_734, metaWritten_1_load_reg_738, tmp_17_i_reg_794)
    begin
                ap_predicate_op159_write_state2 <= ((metaWritten_1_load_reg_738 = ap_const_lv1_0) and (state_1_load_reg_734 = ap_const_lv2_3) and (tmp_17_i_reg_794 = ap_const_lv1_1));
    end process;


    ap_predicate_op30_read_state1_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1)
    begin
                ap_predicate_op30_read_state1 <= ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_2));
    end process;


    ap_predicate_op63_read_state1_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1)
    begin
                ap_predicate_op63_read_state1 <= ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_1));
    end process;


    ap_predicate_op93_read_state1_assign_proc : process(grp_nbreadreq_fu_142_p3, state_1)
    begin
                ap_predicate_op93_read_state1 <= ((grp_nbreadreq_fu_142_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv2_3));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_319_p3 <= rx_shift2exhFifo_dout(576 downto 576);
    grp_nbreadreq_fu_142_p3 <= (0=>(rx_shift2exhFifo_empty_n), others=>'-');
    icmp_ln1019_3_fu_702_p2 <= "1" when (tmp_23_i_fu_692_p4 = ap_const_lv2_3) else "0";
    icmp_ln1019_fu_373_p2 <= "1" when (opCode_V = ap_const_lv5_C) else "0";
    icmp_ln1023_fu_444_p2 <= "1" when (opCode_V = ap_const_lv5_11) else "0";
    icmp_ln73_fu_391_p2 <= "1" when (unsigned(add_ln73_fu_385_p2) < unsigned(ap_const_lv5_6)) else "0";
    icmp_ln80_1_fu_504_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_F) else "0";
    icmp_ln80_2_fu_510_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_D) else "0";
    icmp_ln80_3_fu_516_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_11) else "0";
    icmp_ln80_4_fu_540_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_A) else "0";
    icmp_ln80_5_fu_546_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_6) else "0";
    icmp_ln80_6_fu_552_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_C) else "0";
    icmp_ln80_fu_498_p2 <= "1" when (rx_ibh2exh_MetaFifo_dout = ap_const_lv5_10) else "0";
    metaWritten_1_load_load_fu_340_p1 <= metaWritten_1;
    or_ln80_1_fu_528_p2 <= (icmp_ln80_3_fu_516_p2 or icmp_ln80_2_fu_510_p2);
    or_ln80_2_fu_534_p2 <= (or_ln80_fu_522_p2 or or_ln80_1_fu_528_p2);
    or_ln80_3_fu_558_p2 <= (icmp_ln80_6_fu_552_p2 or icmp_ln80_5_fu_546_p2);
    or_ln80_4_fu_564_p2 <= (or_ln80_3_fu_558_p2 or icmp_ln80_4_fu_540_p2);
    or_ln80_5_fu_578_p2 <= (or_ln80_4_fu_564_p2 or or_ln80_2_fu_534_p2);
    or_ln80_fu_522_p2 <= (icmp_ln80_fu_498_p2 or icmp_ln80_1_fu_504_p2);
    p_Result_s_fu_638_p5 <= (((tmp_22_i_fu_628_p4 & tmp_21_i_fu_618_p4) & tmp_20_i_fu_608_p4) & tmp_19_i_fu_598_p4);
    p_s_fu_683_p3 <= (ap_phi_reg_pp0_iter1_p_Val2_9_reg_301 & ap_const_lv17_0);
    rdmaHeader_ready_load_load_fu_344_p1 <= rdmaHeader_ready;
    ret_V_fu_654_p2 <= std_logic_vector(unsigned(zext_ln1495_fu_650_p1) + unsigned(ap_const_lv33_FFF));

    rx_exh2dropFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_exh2dropFifo_full_n, ap_predicate_op143_write_state2, ap_predicate_op146_write_state2, ap_predicate_op157_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op157_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op146_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op143_write_state2 = ap_const_boolean_1)))) then 
            rx_exh2dropFifo_blk_n <= rx_exh2dropFifo_full_n;
        else 
            rx_exh2dropFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_exh2dropFifo_din <= reg_327;

    rx_exh2dropFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op143_write_state2, ap_predicate_op146_write_state2, ap_predicate_op157_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op157_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op146_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op143_write_state2 = ap_const_boolean_1)))) then 
            rx_exh2dropFifo_write <= ap_const_logic_1;
        else 
            rx_exh2dropFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_exh2drop_MetaFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_exh2drop_MetaFifo_full_n, ap_predicate_op141_write_state2, ap_predicate_op155_write_state2, ap_predicate_op159_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op159_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op155_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)))) then 
            rx_exh2drop_MetaFifo_blk_n <= rx_exh2drop_MetaFifo_full_n;
        else 
            rx_exh2drop_MetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_exh2drop_MetaFifo_din_assign_proc : process(ap_predicate_op141_write_state2, ap_predicate_op155_write_state2, ap_predicate_op159_write_state2, p_s_fu_683_p3, zext_ln212_fu_729_p1, ap_condition_393)
    begin
        if ((ap_const_boolean_1 = ap_condition_393)) then
            if ((ap_predicate_op159_write_state2 = ap_const_boolean_1)) then 
                rx_exh2drop_MetaFifo_din <= ap_const_lv145_lc_3;
            elsif ((ap_predicate_op155_write_state2 = ap_const_boolean_1)) then 
                rx_exh2drop_MetaFifo_din <= zext_ln212_fu_729_p1;
            elsif ((ap_predicate_op141_write_state2 = ap_const_boolean_1)) then 
                rx_exh2drop_MetaFifo_din <= p_s_fu_683_p3;
            else 
                rx_exh2drop_MetaFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_exh2drop_MetaFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_exh2drop_MetaFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op141_write_state2, ap_predicate_op155_write_state2, ap_predicate_op159_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op159_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op155_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op141_write_state2 = ap_const_boolean_1)))) then 
            rx_exh2drop_MetaFifo_write <= ap_const_logic_1;
        else 
            rx_exh2drop_MetaFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_exhMetaFifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_exhMetaFifo_full_n, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, ap_predicate_op152_write_state2, ap_predicate_op158_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op152_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op138_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)))) then 
            rx_exhMetaFifo_blk_n <= rx_exhMetaFifo_full_n;
        else 
            rx_exhMetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_exhMetaFifo_din_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, ap_predicate_op152_write_state2, ap_predicate_op158_write_state2, ap_block_pp0_stage0_01001, zext_ln240_fu_678_p1, zext_ln211_fu_716_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op152_write_state2 = ap_const_boolean_1))) then 
            rx_exhMetaFifo_din <= zext_ln211_fu_716_p1;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op138_write_state2 = ap_const_boolean_1))) then 
            rx_exhMetaFifo_din <= zext_ln240_fu_678_p1;
        elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)))) then 
            rx_exhMetaFifo_din <= ap_const_lv25_2;
        else 
            rx_exhMetaFifo_din <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_exhMetaFifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op126_write_state2, ap_predicate_op138_write_state2, ap_predicate_op152_write_state2, ap_predicate_op158_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op158_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op152_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op138_write_state2 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op126_write_state2 = ap_const_boolean_1)))) then 
            rx_exhMetaFifo_write <= ap_const_logic_1;
        else 
            rx_exhMetaFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_ibh2exh_MetaFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_ibh2exh_MetaFifo_empty_n, ap_predicate_op104_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if (((ap_done_reg = ap_const_logic_0) and (ap_predicate_op104_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_ibh2exh_MetaFifo_blk_n <= rx_ibh2exh_MetaFifo_empty_n;
        else 
            rx_ibh2exh_MetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_ibh2exh_MetaFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op104_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op104_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            rx_ibh2exh_MetaFifo_read <= ap_const_logic_1;
        else 
            rx_ibh2exh_MetaFifo_read <= ap_const_logic_0;
        end if; 
    end process;


    rx_shift2exhFifo_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, rx_shift2exhFifo_empty_n, ap_predicate_op30_read_state1, ap_predicate_op63_read_state1, ap_predicate_op93_read_state1, ap_done_reg, ap_block_pp0_stage0)
    begin
        if ((((ap_done_reg = ap_const_logic_0) and (ap_predicate_op93_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_done_reg = ap_const_logic_0) and (ap_predicate_op63_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_done_reg = ap_const_logic_0) and (ap_predicate_op30_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            rx_shift2exhFifo_blk_n <= rx_shift2exhFifo_empty_n;
        else 
            rx_shift2exhFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_shift2exhFifo_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op30_read_state1, ap_predicate_op63_read_state1, ap_predicate_op93_read_state1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op93_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op63_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op30_read_state1 = ap_const_boolean_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            rx_shift2exhFifo_read <= ap_const_logic_1;
        else 
            rx_shift2exhFifo_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln80_1_fu_584_p3 <= 
        select_ln80_fu_570_p3 when (or_ln80_5_fu_578_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln80_fu_570_p3 <= 
        ap_const_lv2_2 when (or_ln80_4_fu_564_p2(0) = '1') else 
        ap_const_lv2_1;
    shl_ln1_fu_670_p3 <= (tmp_fu_660_p4 & ap_const_lv1_0);
    shl_ln2_fu_721_p3 <= (ap_phi_reg_pp0_iter1_p_Val2_10_reg_310 & ap_const_lv17_0);
    tmp_12_fu_427_p1 <= rx_shift2exhFifo_dout(32 - 1 downto 0);
    tmp_13_fu_356_p1 <= rx_shift2exhFifo_dout(128 - 1 downto 0);
    tmp_19_i_fu_598_p4 <= ap_phi_reg_pp0_iter1_p_Val2_9_reg_301(127 downto 120);
    tmp_20_i_fu_608_p4 <= ap_phi_reg_pp0_iter1_p_Val2_9_reg_301(119 downto 112);
    tmp_21_i_fu_618_p4 <= ap_phi_reg_pp0_iter1_p_Val2_9_reg_301(111 downto 104);
    tmp_22_i_fu_628_p4 <= ap_phi_reg_pp0_iter1_p_Val2_9_reg_301(103 downto 96);
    tmp_23_i_fu_692_p4 <= ap_phi_reg_pp0_iter1_p_Val2_10_reg_310(6 downto 5);
    tmp_fu_660_p4 <= ret_V_fu_654_p2(32 downto 12);
    tmp_i_nbreadreq_fu_156_p3 <= (0=>(rx_ibh2exh_MetaFifo_empty_n), others=>'-');
    zext_ln1495_fu_650_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_s_fu_638_p5),33));
    zext_ln211_cast_fu_708_p3 <= (ap_const_lv1_1 & icmp_ln1019_3_fu_702_p2);
    zext_ln211_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln211_cast_fu_708_p3),25));
    zext_ln212_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_721_p3),145));
    zext_ln240_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_670_p3),25));
end behav;
