// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rocev2_top_handle_read_requests_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rx_readRequestFifo_dout,
        rx_readRequestFifo_num_data_valid,
        rx_readRequestFifo_fifo_cap,
        rx_readRequestFifo_empty_n,
        rx_readRequestFifo_read,
        rx_remoteMemCmd_din,
        rx_remoteMemCmd_num_data_valid,
        rx_remoteMemCmd_fifo_cap,
        rx_remoteMemCmd_full_n,
        rx_remoteMemCmd_write,
        rx_readEvenFifo_din,
        rx_readEvenFifo_num_data_valid,
        rx_readEvenFifo_fifo_cap,
        rx_readEvenFifo_full_n,
        rx_readEvenFifo_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [144:0] rx_readRequestFifo_dout;
input  [3:0] rx_readRequestFifo_num_data_valid;
input  [3:0] rx_readRequestFifo_fifo_cap;
input   rx_readRequestFifo_empty_n;
output   rx_readRequestFifo_read;
output  [149:0] rx_remoteMemCmd_din;
input  [9:0] rx_remoteMemCmd_num_data_valid;
input  [9:0] rx_remoteMemCmd_fifo_cap;
input   rx_remoteMemCmd_full_n;
output   rx_remoteMemCmd_write;
output  [177:0] rx_readEvenFifo_din;
input  [9:0] rx_readEvenFifo_num_data_valid;
input  [9:0] rx_readEvenFifo_fifo_cap;
input   rx_readEvenFifo_full_n;
output   rx_readEvenFifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rx_readRequestFifo_read;
reg[149:0] rx_remoteMemCmd_din;
reg rx_remoteMemCmd_write;
reg[177:0] rx_readEvenFifo_din;
reg rx_readEvenFifo_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] hrr_fsmState_load_load_fu_259_p1;
wire   [0:0] tmp_i_nbreadreq_fu_92_p3;
reg    ap_predicate_op22_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] hrr_fsmState_load_reg_519;
reg   [0:0] tmp_i_reg_533;
reg    ap_predicate_op64_write_state2;
reg    ap_predicate_op67_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] hrr_fsmState;
reg   [63:0] request_vaddr_V;
reg   [31:0] request_dma_length_V;
reg   [23:0] request_qpn_V;
reg   [23:0] request_psn_V;
reg   [0:0] request_host_V;
reg    rx_readRequestFifo_blk_n;
wire    ap_block_pp0_stage0;
reg    rx_remoteMemCmd_blk_n;
reg    rx_readEvenFifo_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] request_vaddr_V_load_reg_523;
wire   [23:0] trunc_ln145_fu_271_p1;
reg   [23:0] trunc_ln145_reg_537;
reg   [23:0] trunc_ln145_s_reg_542;
reg   [0:0] tmp_reg_547;
wire   [63:0] trunc_ln145_4_fu_293_p4;
reg   [63:0] trunc_ln145_4_reg_552;
wire   [31:0] readLength_fu_304_p4;
wire   [15:0] trunc_ln174_12_fu_359_p1;
reg   [15:0] trunc_ln174_12_reg_565;
reg   [63:0] ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_123_p4;
wire   [63:0] add_ln886_11_fu_339_p2;
wire   [63:0] ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_120;
wire   [0:0] icmp_ln1081_1_fu_333_p2;
reg   [31:0] ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_132_p4;
wire   [31:0] add_ln887_1_fu_346_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_129;
reg   [0:0] ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_141_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_138;
wire   [0:0] icmp_ln1081_fu_363_p2;
reg   [63:0] ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_152_p4;
wire   [63:0] add_ln886_fu_375_p2;
wire   [63:0] ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_149;
reg   [31:0] ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_162_p4;
wire   [31:0] add_ln887_fu_382_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_159;
reg   [0:0] ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_172_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_169;
reg   [63:0] ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_186_p6;
wire   [63:0] ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_183;
reg   [31:0] ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_200_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_197;
wire   [31:0] ap_phi_reg_pp0_iter0_readLength_2_reg_211;
reg   [31:0] ap_phi_reg_pp0_iter1_readLength_2_reg_211;
wire   [4:0] ap_phi_reg_pp0_iter0_readOpcode_1_reg_222;
reg   [4:0] ap_phi_reg_pp0_iter1_readOpcode_1_reg_222;
wire   [31:0] ap_phi_reg_pp0_iter0_readLength_1_reg_235;
reg   [31:0] ap_phi_reg_pp0_iter1_readLength_1_reg_235;
wire   [1:0] ap_phi_reg_pp0_iter0_readOpcode_reg_246;
reg   [1:0] ap_phi_reg_pp0_iter1_readOpcode_reg_246;
wire   [23:0] add_ln886_10_fu_454_p2;
wire   [149:0] zext_ln174_89_fu_418_p1;
reg    ap_block_pp0_stage0_01001;
wire   [149:0] zext_ln174_fu_493_p1;
wire   [177:0] zext_ln174_90_fu_437_p1;
wire   [177:0] zext_ln174_88_fu_514_p1;
wire   [31:0] zext_ln901_1_fu_401_p1;
wire   [145:0] or_ln174_161_i_fu_405_p7;
wire   [176:0] or_ln174_163_i_cast_fu_423_p7;
wire  signed [3:0] sext_ln901_fu_442_p1;
wire   [15:0] trunc_ln174_fu_474_p1;
wire   [31:0] zext_ln901_fu_446_p1;
wire   [145:0] or_ln174_158_i_fu_478_p7;
wire   [176:0] or_ln174_160_i_cast_fu_498_p7;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_170;
reg    ap_condition_173;
reg    ap_condition_176;
reg    ap_condition_410;
reg    ap_condition_246;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 hrr_fsmState = 1'd0;
#0 request_vaddr_V = 64'd0;
#0 request_dma_length_V = 32'd0;
#0 request_qpn_V = 24'd0;
#0 request_psn_V = 24'd0;
#0 request_host_V = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_170)) begin
        if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_readLength_1_reg_235 <= request_dma_length_V;
        end else if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_readLength_1_reg_235 <= 32'd4096;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_readLength_1_reg_235 <= ap_phi_reg_pp0_iter0_readLength_1_reg_235;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_170)) begin
        if ((1'b1 == ap_condition_176)) begin
            ap_phi_reg_pp0_iter1_readLength_2_reg_211 <= {{rx_readRequestFifo_dout[119:88]}};
        end else if ((1'b1 == ap_condition_173)) begin
            ap_phi_reg_pp0_iter1_readLength_2_reg_211 <= 32'd4096;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_readLength_2_reg_211 <= ap_phi_reg_pp0_iter0_readLength_2_reg_211;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_170)) begin
        if ((1'b1 == ap_condition_176)) begin
            ap_phi_reg_pp0_iter1_readOpcode_1_reg_222 <= 5'd16;
        end else if ((1'b1 == ap_condition_173)) begin
            ap_phi_reg_pp0_iter1_readOpcode_1_reg_222 <= 5'd13;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_readOpcode_1_reg_222 <= ap_phi_reg_pp0_iter0_readOpcode_1_reg_222;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_170)) begin
        if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_readOpcode_reg_246 <= 2'd3;
        end else if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_readOpcode_reg_246 <= 2'd2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_readOpcode_reg_246 <= ap_phi_reg_pp0_iter0_readOpcode_reg_246;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_170)) begin
        if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd0))) begin
            hrr_fsmState <= 1'd0;
        end else if ((1'b1 == ap_condition_173)) begin
            hrr_fsmState <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_410)) begin
            request_psn_V <= {{rx_readRequestFifo_dout[143:120]}};
        end else if (((hrr_fsmState_load_reg_519 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            request_psn_V <= add_ln886_10_fu_454_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hrr_fsmState_load_reg_519 <= hrr_fsmState;
        request_vaddr_V_load_reg_523 <= request_vaddr_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_172_p6 == 1'd1))) begin
        request_dma_length_V <= ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_200_p6;
        request_vaddr_V <= ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_186_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        request_host_V <= rx_readRequestFifo_dout[32'd144];
        request_qpn_V <= trunc_ln145_fu_271_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (hrr_fsmState == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i_reg_533 <= tmp_i_nbreadreq_fu_92_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_547 <= rx_readRequestFifo_dout[32'd144];
        trunc_ln145_4_reg_552 <= {{rx_readRequestFifo_dout[87:24]}};
        trunc_ln145_reg_537 <= trunc_ln145_fu_271_p1;
        trunc_ln145_s_reg_542 <= {{rx_readRequestFifo_dout[143:120]}};
        trunc_ln174_12_reg_565 <= trunc_ln174_12_fu_359_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0))) begin
        if ((icmp_ln1081_1_fu_333_p2 == 1'd0)) begin
            ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_132_p4 = {{rx_readRequestFifo_dout[119:88]}};
        end else if ((icmp_ln1081_1_fu_333_p2 == 1'd1)) begin
            ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_132_p4 = add_ln887_1_fu_346_p2;
        end else begin
            ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_132_p4 = ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_129;
        end
    end else begin
        ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_132_p4 = ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_129;
    end
end

always @ (*) begin
    if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd1))) begin
        ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_162_p4 = add_ln887_fu_382_p2;
    end else begin
        ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_162_p4 = ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_159;
    end
end

always @ (*) begin
    if (((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0))) begin
        ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_200_p6 = ap_phi_mux_request_dma_length_V_new_0_i_phi_fu_132_p4;
    end else if ((hrr_fsmState_load_load_fu_259_p1 == 1'd1)) begin
        ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_200_p6 = ap_phi_mux_request_dma_length_V_new_2_i_phi_fu_162_p4;
    end else begin
        ap_phi_mux_request_dma_length_V_new_3_i_phi_fu_200_p6 = ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_197;
    end
end

always @ (*) begin
    if ((hrr_fsmState_load_load_fu_259_p1 == 1'd1)) begin
        if ((icmp_ln1081_fu_363_p2 == 1'd0)) begin
            ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_141_p4 = 1'd0;
        end else if ((icmp_ln1081_fu_363_p2 == 1'd1)) begin
            ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_141_p4 = 1'd1;
        end else begin
            ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_141_p4 = ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_138;
        end
    end else begin
        ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_141_p4 = ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_138;
    end
end

always @ (*) begin
    if (((tmp_i_nbreadreq_fu_92_p3 == 1'd0) & (hrr_fsmState == 1'd0))) begin
        ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_172_p6 = 1'd0;
    end else if (((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0))) begin
        ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_172_p6 = 1'd1;
    end else if ((hrr_fsmState_load_load_fu_259_p1 == 1'd1)) begin
        ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_172_p6 = ap_phi_mux_request_vaddr_V_flag_2_i_phi_fu_141_p4;
    end else begin
        ap_phi_mux_request_vaddr_V_flag_3_i_phi_fu_172_p6 = ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_169;
    end
end

always @ (*) begin
    if (((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0))) begin
        if ((icmp_ln1081_1_fu_333_p2 == 1'd0)) begin
            ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_123_p4 = {{rx_readRequestFifo_dout[87:24]}};
        end else if ((icmp_ln1081_1_fu_333_p2 == 1'd1)) begin
            ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_123_p4 = add_ln886_11_fu_339_p2;
        end else begin
            ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_123_p4 = ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_120;
        end
    end else begin
        ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_123_p4 = ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_120;
    end
end

always @ (*) begin
    if (((hrr_fsmState_load_load_fu_259_p1 == 1'd1) & (icmp_ln1081_fu_363_p2 == 1'd1))) begin
        ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_152_p4 = add_ln886_fu_375_p2;
    end else begin
        ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_152_p4 = ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_149;
    end
end

always @ (*) begin
    if (((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0))) begin
        ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_186_p6 = ap_phi_mux_request_vaddr_V_new_0_i_phi_fu_123_p4;
    end else if ((hrr_fsmState_load_load_fu_259_p1 == 1'd1)) begin
        ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_186_p6 = ap_phi_mux_request_vaddr_V_new_2_i_phi_fu_152_p4;
    end else begin
        ap_phi_mux_request_vaddr_V_new_3_i_phi_fu_186_p6 = ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_183;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (hrr_fsmState_load_reg_519 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op67_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rx_readEvenFifo_blk_n = rx_readEvenFifo_full_n;
    end else begin
        rx_readEvenFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_246)) begin
        if ((hrr_fsmState_load_reg_519 == 1'd1)) begin
            rx_readEvenFifo_din = zext_ln174_88_fu_514_p1;
        end else if ((ap_predicate_op67_write_state2 == 1'b1)) begin
            rx_readEvenFifo_din = zext_ln174_90_fu_437_p1;
        end else begin
            rx_readEvenFifo_din = 'bx;
        end
    end else begin
        rx_readEvenFifo_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (hrr_fsmState_load_reg_519 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op67_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rx_readEvenFifo_write = 1'b1;
    end else begin
        rx_readEvenFifo_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_predicate_op22_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_readRequestFifo_blk_n = rx_readRequestFifo_empty_n;
    end else begin
        rx_readRequestFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op22_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_readRequestFifo_read = 1'b1;
    end else begin
        rx_readRequestFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (hrr_fsmState_load_reg_519 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op64_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rx_remoteMemCmd_blk_n = rx_remoteMemCmd_full_n;
    end else begin
        rx_remoteMemCmd_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_246)) begin
        if ((hrr_fsmState_load_reg_519 == 1'd1)) begin
            rx_remoteMemCmd_din = zext_ln174_fu_493_p1;
        end else if ((ap_predicate_op64_write_state2 == 1'b1)) begin
            rx_remoteMemCmd_din = zext_ln174_89_fu_418_p1;
        end else begin
            rx_remoteMemCmd_din = 'bx;
        end
    end else begin
        rx_remoteMemCmd_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (hrr_fsmState_load_reg_519 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op64_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rx_remoteMemCmd_write = 1'b1;
    end else begin
        rx_remoteMemCmd_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln886_10_fu_454_p2 = (request_psn_V + 24'd1);

assign add_ln886_11_fu_339_p2 = (trunc_ln145_4_fu_293_p4 + 64'd4096);

assign add_ln886_fu_375_p2 = (request_vaddr_V + 64'd4096);

assign add_ln887_1_fu_346_p2 = ($signed(readLength_fu_304_p4) + $signed(32'd4294963200));

assign add_ln887_fu_382_p2 = ($signed(request_dma_length_V) + $signed(32'd4294963200));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((hrr_fsmState_load_reg_519 == 1'd1) & (rx_remoteMemCmd_full_n == 1'b0)) | ((ap_predicate_op67_write_state2 == 1'b1) & (rx_readEvenFifo_full_n == 1'b0)) | ((rx_readEvenFifo_full_n == 1'b0) & (hrr_fsmState_load_reg_519 == 1'd1)) | ((ap_predicate_op64_write_state2 == 1'b1) & (rx_remoteMemCmd_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op22_read_state1 == 1'b1) & (rx_readRequestFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((hrr_fsmState_load_reg_519 == 1'd1) & (rx_remoteMemCmd_full_n == 1'b0)) | ((ap_predicate_op67_write_state2 == 1'b1) & (rx_readEvenFifo_full_n == 1'b0)) | ((rx_readEvenFifo_full_n == 1'b0) & (hrr_fsmState_load_reg_519 == 1'd1)) | ((ap_predicate_op64_write_state2 == 1'b1) & (rx_remoteMemCmd_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op22_read_state1 == 1'b1) & (rx_readRequestFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((hrr_fsmState_load_reg_519 == 1'd1) & (rx_remoteMemCmd_full_n == 1'b0)) | ((ap_predicate_op67_write_state2 == 1'b1) & (rx_readEvenFifo_full_n == 1'b0)) | ((rx_readEvenFifo_full_n == 1'b0) & (hrr_fsmState_load_reg_519 == 1'd1)) | ((ap_predicate_op64_write_state2 == 1'b1) & (rx_remoteMemCmd_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op22_read_state1 == 1'b1) & (rx_readRequestFifo_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_predicate_op22_read_state1 == 1'b1) & (rx_readRequestFifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((hrr_fsmState_load_reg_519 == 1'd1) & (rx_remoteMemCmd_full_n == 1'b0)) | ((ap_predicate_op67_write_state2 == 1'b1) & (rx_readEvenFifo_full_n == 1'b0)) | ((rx_readEvenFifo_full_n == 1'b0) & (hrr_fsmState_load_reg_519 == 1'd1)) | ((ap_predicate_op64_write_state2 == 1'b1) & (rx_remoteMemCmd_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_170 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_173 = ((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0) & (icmp_ln1081_1_fu_333_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_176 = ((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0) & (icmp_ln1081_1_fu_333_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_246 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_410 = ((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0) & (ap_start == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_readLength_1_reg_235 = 'bx;

assign ap_phi_reg_pp0_iter0_readLength_2_reg_211 = 'bx;

assign ap_phi_reg_pp0_iter0_readOpcode_1_reg_222 = 'bx;

assign ap_phi_reg_pp0_iter0_readOpcode_reg_246 = 'bx;

assign ap_phi_reg_pp0_iter0_request_dma_length_V_new_0_i_reg_129 = 'bx;

assign ap_phi_reg_pp0_iter0_request_dma_length_V_new_2_i_reg_159 = 'bx;

assign ap_phi_reg_pp0_iter0_request_dma_length_V_new_3_i_reg_197 = 'bx;

assign ap_phi_reg_pp0_iter0_request_vaddr_V_flag_2_i_reg_138 = 'bx;

assign ap_phi_reg_pp0_iter0_request_vaddr_V_flag_3_i_reg_169 = 'bx;

assign ap_phi_reg_pp0_iter0_request_vaddr_V_new_0_i_reg_120 = 'bx;

assign ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_i_reg_149 = 'bx;

assign ap_phi_reg_pp0_iter0_request_vaddr_V_new_3_i_reg_183 = 'bx;

always @ (*) begin
    ap_predicate_op22_read_state1 = ((tmp_i_nbreadreq_fu_92_p3 == 1'd1) & (hrr_fsmState == 1'd0));
end

always @ (*) begin
    ap_predicate_op64_write_state2 = ((tmp_i_reg_533 == 1'd1) & (hrr_fsmState_load_reg_519 == 1'd0));
end

always @ (*) begin
    ap_predicate_op67_write_state2 = ((tmp_i_reg_533 == 1'd1) & (hrr_fsmState_load_reg_519 == 1'd0));
end

assign hrr_fsmState_load_load_fu_259_p1 = hrr_fsmState;

assign icmp_ln1081_1_fu_333_p2 = ((readLength_fu_304_p4 > 32'd4096) ? 1'b1 : 1'b0);

assign icmp_ln1081_fu_363_p2 = ((request_dma_length_V > 32'd4096) ? 1'b1 : 1'b0);

assign or_ln174_158_i_fu_478_p7 = {{{{{{{{{{1'd0}, {request_host_V}}}, {ap_phi_reg_pp0_iter1_readLength_1_reg_235}}}, {request_vaddr_V_load_reg_523}}}, {trunc_ln174_fu_474_p1}}}, {zext_ln901_fu_446_p1}};

assign or_ln174_160_i_cast_fu_498_p7 = {{{{{{{{{{1'd1}, {add_ln886_10_fu_454_p2}}}, {ap_phi_reg_pp0_iter1_readLength_1_reg_235}}}, {64'd0}}}, {request_qpn_V}}}, {zext_ln901_fu_446_p1}};

assign or_ln174_161_i_fu_405_p7 = {{{{{{{{{{1'd0}, {tmp_reg_547}}}, {ap_phi_reg_pp0_iter1_readLength_2_reg_211}}}, {trunc_ln145_4_reg_552}}}, {trunc_ln174_12_reg_565}}}, {zext_ln901_1_fu_401_p1}};

assign or_ln174_163_i_cast_fu_423_p7 = {{{{{{{{{{1'd1}, {trunc_ln145_s_reg_542}}}, {ap_phi_reg_pp0_iter1_readLength_2_reg_211}}}, {64'd0}}}, {trunc_ln145_reg_537}}}, {zext_ln901_1_fu_401_p1}};

assign readLength_fu_304_p4 = {{rx_readRequestFifo_dout[119:88]}};

assign sext_ln901_fu_442_p1 = $signed(ap_phi_reg_pp0_iter1_readOpcode_reg_246);

assign tmp_i_nbreadreq_fu_92_p3 = rx_readRequestFifo_empty_n;

assign trunc_ln145_4_fu_293_p4 = {{rx_readRequestFifo_dout[87:24]}};

assign trunc_ln145_fu_271_p1 = rx_readRequestFifo_dout[23:0];

assign trunc_ln174_12_fu_359_p1 = rx_readRequestFifo_dout[15:0];

assign trunc_ln174_fu_474_p1 = request_qpn_V[15:0];

assign zext_ln174_88_fu_514_p1 = or_ln174_160_i_cast_fu_498_p7;

assign zext_ln174_89_fu_418_p1 = or_ln174_161_i_fu_405_p7;

assign zext_ln174_90_fu_437_p1 = or_ln174_163_i_cast_fu_423_p7;

assign zext_ln174_fu_493_p1 = or_ln174_158_i_fu_478_p7;

assign zext_ln901_1_fu_401_p1 = ap_phi_reg_pp0_iter1_readOpcode_1_reg_222;

assign zext_ln901_fu_446_p1 = $unsigned(sext_ln901_fu_442_p1);

endmodule //rocev2_top_handle_read_requests_0_s
